r-lib/pkgdown

R/build-index.r, R/build.r, R/package.r, R/util.r, man/as.sd_package.Rd, man/build_site.Rd
This resolves #69 (and also resolves #59 - a duplicate of #59) as well as some minor improvements associated with #70 (Update documentation)
=> Fixes bug that requires inst/staticdocs to exist, even if site_path is specified

R/rd.r, man/parse_rd.Rd
Who said I don't like recursion?
=> Fix the print method for Rd_content, bringing back parse_rd

R/highlight.r, R/replay-html.r, R/to-html.r
`src_highlight` has multiple bugs and can’t work. this fixes them (and #110)
=> Unbreak src_highlight

R/to-html.r
of `link[my.package]{topic}` (#115).
=> Move special-case handling

docs/build_site.html, docs/demo-plot.html, docs/demo-stats.html, docs/index.html, docs/parse_rd.html, docs/reference.html, docs/render_page.html, docs/sd_icon.html, docs/sd_item.html, docs/sd_section.html, docs/to_html.html, inst/templates/head.html
jquery is need for navbar of narrow screen
=> need jquery to make navbar responsive

R/build-news.R, R/build.r, man/build_news.Rd, man/build_site.Rd
I am not the only one that needs clarity on the NEWS.md format, see #166
=> Small improvements, see commit messages

R/build-reference.R
- so that output filenames are named with topic name rather than "unknown"
=> add missing topic param

R/build-news.R
This affects the display in the sidebar.
=> Support dash as separator for version components

R/build-home-authors.R
=> Remove unused function itemize()

R/build-reference.R, R/rd-html.R
necessary for DBI, but (in theory) could also occur in the wild.
https://github.com/hadley/pkgdown/commit/e356925a074411d71ba20c9ca518ceab0143e6a4#commitcomment-20050894
@hadley: PTAL.
=> Support links to the same package

R/build-reference.R, R/rd-html.R, tests/testthat/test-as_html.R
Regression from #242. Fixes #243.
Sorry -- I wasn't aware we now have tests that can fail... Thanks @jranke.
=> Fix failing test

R/build-articles.R, R/build-home.R, R/util.r, tests/testthat/test-tweak.R
* New `tweak_tables()`.
* This function is called also from `tweak_homepage_html()`.
=> Add class=table also to tables in home

R/build-reference-index.R
=> Trivial: use == instead of %in%

R/render.r
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hadley/pkgdown/264)
=> typo. duplicated word

R/rd.r
=> Adding a explicit option to the loadPkgRdMacros

R/rd-data.R
for rendering dplyr.benchmark.
=> Fix processing of links in \value{}

R/build-articles.R
Sorry for the slightly messy commit due to text reflow. Only change to actual text is in doc for pkg argument (ref. #296).
=> better docs for pkg argument to "build_" functions

R/rd-html.R, tests/testthat/test-as_html.R
Fix tabular -> html (#348)
ads test
=> Bugfix tabular

R/build-articles.R, R/util.r
fixes #334, tweak TOC  anchors with a period in article page
=> fixes #334 tweak TOC anchors with a period

DESCRIPTION, R/build-reference.R
@hadley: This is for tic, could you please take a look?
Link to successful build: https://travis-ci.org/krlmlr/tic.package#L1312 .
=> Use pkgload instead of devtools

docs/pkgdown.js, inst/assets/pkgdown.js
Fixes #326
@jjallaire / @wch could you please take a look and make sure I haven't done anything stupid in the javascript. It appears to work.
=> Use js to indicate activate nav category

R/bacon.R, R/rd-data.R, docs/authors.html, docs/index.html, docs/reference/pulledpork.html, man/pulledpork.Rd
Currently, example code inside `\dontshow{}` is not run. This pull request fixes that.
The documentation for pulled pork in `bacon.R` now includes an example to verify this.
=> Ensure example code inside `\dontshow{}` is run

R/build-home.R
=> do home README.Rmd rendering with globalenv

R/util.r, tests/testthat/news/DESCRIPTION, tests/testthat/news/NEWS.md, tests/testthat/test-build_news.R
Fixes #500 NEWS.md is no longer populating docs/news/index.html
Partner in crime: @jimhester
=> Rescue NEWS

R/build-home.R
Generate pkgdown data first for `data_home_sidebar()`
=> generate pkgdown data first

R/build-articles.R, R/build-home.R, R/build-news.R, R/build-reference.R, R/build.r, man/build_articles.Rd, man/build_home.Rd, man/build_news.Rd, man/build_reference.Rd
=> Allows auto-preview on build_home(), build_reference(), etc

R/build.r
=> Add note for clean_site in build_site

R/build-home-citation.R
=> fix authors page for named Authors@R

inst/templates/docsearch.html
=> add option for docsearch appId

R/build-search-docs.R
instead of the package name. also test for its existence.
=> populate index_name from _pkgdown.yml

inst/templates/head.html
they updated their JS snippet.
=> update Google Analytics tracking code

NEWS.md, R/package.r, vignettes/pkgdown.Rmd
=> check for inst/pkgdown.yml

inst/assets/pkgdown.css
Closes https://github.com/r-lib/pkgdown/issues/667.
=> Add 10px bottom margin to htmlwidgets

NEWS.md, R/html-tweak.R, tests/testthat/assets/site-dot-github/.github/CODE_OF_CONDUCT.md, tests/testthat/assets/site-dot-github/DESCRIPTION, tests/testthat/assets/site-dot-github/README.Rmd, tests/testthat/test-build_home.R
=> Correctly link files in .github

NEWS.md, R/build.r, inst/templates/head.html
=> config option to suppress web indexing

tests/testthat/test-rd-html.R
=> Diagnose covr failure

.Rbuildignore, tests/testthat/test-build_home.R
And skip during CMD CHECK
Closes #705
=> Build-ignore .github in test

NEWS.md
* Separate bullets for keyboard shortcut for search, and Aloglia logo.
=> Separate news bullets

DESCRIPTION, R/github.R, R/html-tweak.R, tests/testthat/test-link-href.R
Refactor github link parsing using the usethis strategy
Fixes #733
=> Make github link parsing more robust

R/github.R, tests/testthat/assets/news-github-links/NEWS.md, tests/testthat/test-build-news.R
=> Allow hyphens in github username

R/html-tweak.R, tests/testthat/test-html-tweak.R
=> prepend, not replace existing table classes with .table

DESCRIPTION, NEWS.md, R/build-home-index.R, R/build-news.R, R/utils.r, tests/testthat/test-utils.R
=> Check for internet connectivity

DESCRIPTION, NEWS.md, R/build-home-index.R, R/build-news.R, R/utils.r, tests/testthat/test-utils.R
Reverts f36683c2e4582a9e75f1608556559d0aeaf370e1
=> Don't check for internet connection

R/build-cname.R, tests/testthat/test-build-cname.R
=> Skip CNAME creation for URLs with paths

R/html-tweak.R, tests/testthat/test-html-tweak.R
=> Handle multiple tables in tweak_tables.

inst/assets/pkgdown.js, inst/templates/head.html
Update jquery and Clipboard.JS versions
=> JS lib updates

vignettes/pkgdown.Rmd
The contributing guide says to not directly edit generated files such as `.Rd` files I'm not entirely clear whether I should rebuild the website or not once I edited the source file.
=> Fix typo (crawlwer)

NEWS.md, R/usage.R, tests/testthat/test-usage.R
=> Handle usage statements with namespaces

R/deploy-site.R
=> When deploying, perform shallow clone

NEWS.md, inst/assets/pkgdown.css, inst/templates/content-reference-index.html
This fixes problem with https://ggplot2.tidyverse.org/reference/index.html
=> Ensure icon column has some space

R/deploy-site.R
Including refactoring into smaller functions so it's easier to test locally
(I actually tested it locally and it works: https://github.com/r-lib/pkgdown/commits/gh-pages)
Fixes #875
=> Deploy with clone

NEWS.md, R/rd-html.R, tests/testthat/test-rd-html.R
Cleaned up version of #771. Closes #771.
=> Bad Rd tags throw errors

R/link-href.R, R/link-packages.R
=> Update soft-deprecated rlang functions

NEWS.md, R/github.R, tests/testthat/test-github.R
=> Require whitespace or parens before author

R/link-href.R, tests/testthat/test-link-href.R, vignettes/test/highlight.Rmd
=> Prevent spurious href links

NEWS.md, R/html-tweak.R, tests/testthat/test-html-tweak.R, vignettes/test/table.Rmd
=> Fix html table class tweaking

NEWS.md, inst/templates/content-home.html
=> Add headers to home template

inst/templates/navbar.html
=> Hide search box on tablet and smaller

vignettes/pkgdown.Rmd
With @haleyjeppson (👋@lrutter)
=> adds blurb to describe embedding a shiny app, fixes #838

.github/404.md, NEWS.md, R/build-404.R, R/init.R, inst/templates/navbar.html, man/init_site.Rd, tests/testthat/assets/site-dot-github/.github/404.md, tests/testthat/test-build_home.R
Using a default or content from 404.md
Closes #947
=> Create a 404 page

R/usage.R, tests/testthat/test-usage.R
=> Allow NULL return in S4method

NEWS.md, R/build-home-index.R, R/build-home.R, man/build_home.Rd, tests/testthat/test-build-home-index.R
cf https://github.com/r-lib/pkgdown/pull/1005#issuecomment-492178755 from the right branch this time.
I've left the test of the current behavior.
=> rm my title param mistake

NEWS.md, inst/assets/pkgdown.css, inst/assets/pkgdown.js, inst/templates/head.html
=> Use headroom.js to hide the navbar

NEWS.md, R/html-tweak.R, tests/testthat/assets/autolink.Rmd, tests/testthat/assets/autolink.html, tests/testthat/test-autolink_html.R
=> Prevent auto-linking of functions in headers

R/clean.R
=> Check for docs directory

.github/CONTRIBUTING.md, NEWS.md, R/build-home-community.R, R/build-home-index.R, tests/testthat/test-build-home-community.R, vignettes/pkgdown.Rmd
Preview at https://sad-boyd-496480.netlify.com/
Closes #1044
=> Add community files to sidebar

.travis.yml, DESCRIPTION, R/render.r
Fixes error in whisker.render when `_R_CHECK_LENGTH_1_LOGIC2=true`
Needs upstream fix in r-lib/xml2#261
Fixes #1064.
=> Collapse whisker template

DESCRIPTION, R/highlight.r, R/html-tweak.R, R/link-href.R
=> Update deprecated rlang functions

NEWS.md, R/link-href.R, R/usage.R, tests/testthat/test-link-href.R, vignettes/test/rendering.Rmd
=> Link infix operators

vignettes/test/jss.Rmd, vignettes/test/jss.bst, vignettes/test/jss.cls
=> Add JSS assets

DESCRIPTION
r-lib/xml2#261 was merged and released on CRAN
=> Remove dependency on remote xml2

NEWS.md, inst/assets/pkgdown.css
fix #1134 
Tested on latest firefox and chromium.
=> Do not display links when printing

DESCRIPTION
See also https://github.com/r-lib/pkgdown/pull/1014#issuecomment-540546999
=> Increase min required fs version (fix #1141)

NEWS.md, R/build-home-citation.R
changes preview: [https://hungry-haibt-ce507a.netlify.com/authors.html](https://hungry-haibt-ce507a.netlify.com/authors.html)
=> build citation as specified by the textVersion field in CITATION file, fixes #1096

inst/assets/pkgdown.css, inst/templates/content-article.html, inst/templates/content-home.html, inst/templates/content-news.html, inst/templates/content-reference-index.html, inst/templates/content-reference-topic.html
=> Qualify id to avoid collisions

R/build.r, man/build_site.Rd
=> Tweak link

R/rmarkdown.R
=> Remove encoding arg

R/deploy-site.R
Updated link to the Travis package docs, and fixed a typo.
=> Update Travis link

NEWS.md, R/build.r, inst/assets/pkgdown.css, man/build_site.Rd
Fixes #1213.
From @ijlyttle and @wendtke.
We tested the sub-menu functionality on this `pkgdown` [example website](https://wendtke.github.io/pkgdownsubmenu/).
There is an existing error in `master` that might require attention; however, our contributions did not introduce any new errors.
=> Add submenu option

R/build-home-index.R
=> Remove unused build_index()

R/link-topic-index.R
by simplifying default argument in memoized function.
=> Speed up auto-linking

NEWS.md, R/init.R
=> Include a timestamp for site build

NEWS.md, R/build-news.R, inst/assets/bootstrap-toc.css, inst/assets/bootstrap-toc.js, inst/assets/pkgdown.css, inst/assets/pkgdown.js, inst/templates/content-article.html, inst/templates/content-news.html, inst/templates/content-reference-index.html, inst/templates/content-reference-topic.html, inst/templates/head.html, inst/templates/layout.html, tests/testthat/test-build-news.R
Closes #1077. Closes #1254. Closes #817.
=> Use bootstrap-toc for sidebars

R/html-tweak.R, tests/testthat/test-html-tweak.R
=> Fix badge search

NEWS.md, R/highlight.r, R/html-tweak.R, tests/testthat/test-highlight.R, tests/testthat/test-html-tweak.R, tests/testthat/test-rd-html.R, vignettes/pkgdown.Rmd
I'm not sure how I missed this before, but this has clearly been a problem for a long time.
Fixes #1262
=> Check package name before making a remote  link

vignettes/linking.Rmd
update doc to reflect change in 97797b760980f0a058d0a583150b693aed7adc18.
Related: #1210.
=> Also mention `help('topic')` in doc

NEWS.md, R/deploy-site.R, man/deploy_site_github.Rd
=> WIP - Fix travis deploy

.github/workflows/R-CMD-check.yaml, NEWS.md, R/deploy-site.R, man/deploy_site_github.Rd, man/deploy_to_branch.Rd
=> Enable cleaning of deployed site

R/html-build.R, R/rd-html.R, tests/testthat/test-rd-html.R
=> Unescape preformatted text prior to higlhighting

NAMESPACE, R/build-reference.R, R/rd-data.R
=> Add author to reference topic

R/build-articles.R, man/build_articles.Rd
=> document global article frontmatter with _site.yml

NEWS.md, R/init.R, tests/testthat/test-init-meta.txt, tests/testthat/test-init.R
Fixes #1401
Need to think about how to test this so it doesn't happen again.
=> Restore articles index

README.Rmd, README.md
For me it finally only worked when setting the the source to the created gh-pages branch. There was no "docs" folder (as this is added to .gitignore) and I got stuck for quite a while as it did not work. If I set this to the gh-pages branch it seemed to work fine, but maybe I did something wrong.
=> Update README concerning tGithub pages

NEWS.md, inst/templates/head.html, vignettes/pkgdown.Rmd
=> Add google site verification to head

vignettes/pkgdown.Rmd
Maybe it should be mentioned in the metadata vignette too? Asking because of https://community.rstudio.com/t/pkgdown-site-twitter-card-image-not-showing/93409
=> Mention the URL should be in the config file

NEWS.md, inst/templates/BS3/content-article.html, vignettes/test/rendering.Rmd
closes https://github.com/r-lib/pkgdown/issues/1428
=> Ignore subtitle, author, date in article toc

R/build.r
=> Keep source when installing into temporary library

pkgdown/_pkgdown.yml
as I'm working on build_home() docs :-)
=> Add Maëlle's URL

NEWS.md, R/html-tweak.R, R/render.r, tests/testthat/test-html-tweak.R
=> Make links in navbar absolute in 404

R/html-tweak.R, R/package.r
=> Ensure the URL has no trailing slash

R/build-home-authors.R, R/build-home-index.R, R/markdown.R, R/render.r, tests/testthat/_snaps/data_home_sidebar.md, tests/testthat/_snaps/markdown.md, tests/testthat/_snaps/pkgdown_footer.md, tests/testthat/test-build-home-authors.R, tests/testthat/test-markdown.R
=> Refactor and add tests for markdown_text2()

DESCRIPTION, NEWS.md, R/build-articles.R, man/build_articles.Rd, vignettes/test/output-html-vignette.Rmd, vignettes/test/output-theme.Rmd
=> Improve build_articles() logic for theme when as_is

R/build-favicons.R, R/build-logo.R
=> Remove older find_logo() function

NEWS.md, R/html-tweak.R, R/render.r, inst/assets/BS4/pkgdown.css, inst/assets/BS4/pkgdown.js, tests/testthat/test-rmarkdown.R, vignettes/test/rendering.Rmd
=> Add inline footnotes à la bs4_book

inst/assets/BS4/pkgdown.css, inst/templates/BS4/content-article.html, inst/templates/BS4/content-news.html
Fix #1579 + size of TOC header in changelog
=> sidebar fixes

R/navbar.R, tests/testthat/_snaps/navbar.md, tests/testthat/test-navbar.R
=> Fix navbar customization logic

R/html-tweak.R, R/render.r, inst/assets/BS4/pkgdown.css, inst/templates/BS4/content-article-index.html, inst/templates/BS4/content-article.html, inst/templates/BS4/content-authors.html, inst/templates/BS4/content-citation-authors.html, inst/templates/BS4/content-news-index.html, inst/templates/BS4/content-news.html, inst/templates/BS4/content-reference-index.html, inst/templates/BS4/content-reference-topic.html, inst/templates/BS4/content-title-body.html, inst/templates/BS4/content-tutorial-index.html
=> keep logo at the same height by adding padding

man/build_site.Rd, man/rmd-fragments/navbar-configuration.Rmd, vignettes/customization.Rmd
=> add docs for navbar type and bg

R/build.r, R/init.R, R/render.r, man/build_site.Rd, vignettes/customization.Rmd
=> Location for and use of default assets and templates

NEWS.md, R/build-articles.R, man/build_articles.Rd
=> rm TOC depth mention from build_articles() docs

DESCRIPTION, vignettes/customization.Rmd
=> update bslib examples

R/build-news.R, inst/assets/BS4/pkgdown.css
cf https://github.com/r-lib/pkgdown/commit/5b5baea274400b242e0a2194fe9d392f753d3508#commitcomment-49209040 by @jayhesselberth (thank you!)
=> Convert news headings to h2 in the changelog for BS4

inst/assets/BS4/pkgdown.css
Fix  #1617 (the problem wasn't the one I thought)
=> Fix specificity of CSS rule for page header

.github/workflows/pkgdown.yaml, R/render.r
=> Fix path transformation in data_deps()

NEWS.md, R/html-tweak.R, R/navbar.R, R/rd-html.R, inst/assets/BS4/pkgdown.css, inst/templates/BS4/content-reference-index.html, inst/templates/BS4/content-reference-topic.html, man/build_site.Rd, man/rmd-fragments/navbar-configuration.Rmd, tests/testthat/_snaps/build-news.md, tests/testthat/_snaps/navbar.md, tests/testthat/test-rd-html.R
Fix #1553
Fix #782
I am using https://wave.webaim.org/report
* New report https://wave.webaim.org/report#/https://608180fdb7e75958b4657b00--pkgdown-dev.netlify.app/ (this tool does not seem to use aria-hidden, cf also #1636)
* Current report https://wave.webaim.org/report#/https://pkgdown.r-lib.org/dev/
The search form label will be fixed by #1629
=> Accessibility changes

inst/assets/BS4/pkgdown.css, inst/templates/BS4/head.html
(I didn't find related bslib variables)
=> changes from Google Lighthouse report

inst/assets/BS4/pkgdown.css, vignettes/test/rendering.Rmd
=> Fix vertical margin for details

R/html-tweak.R
=> fix logo removal when the logo is in a link

NEWS.md
=> fix all news bullets

NEWS.md, R/repo.R, tests/testthat/test-repo.R
=> preserve URLs with fragments

NEWS.md, R/build-redirects.R, R/build.r, inst/templates/BS3/content-redirect.html, inst/templates/BS4/content-redirect.html, man/build_site.Rd, man/rmd-fragments/redirects-configuration.Rmd, pkgdown/_pkgdown.yml, tests/testthat/_snaps/build-redirects.md, tests/testthat/test-build-redirects.R
=> Add support for redirects

R/build-news.R, R/html-tweak.R, R/markdown.R, R/navbar.R, R/render.r, inst/assets/BS4/syntax-highlighting.css, tests/testthat/_snaps/build-news.md
Fixes #1665.
@maelle can you please finish this off by double checking every place you've used as.character()? Might want to turn this into a wrapper function.
=> Suppress default re-formating of HTML

NEWS.md, R/markdown.R
h/t https://github.com/r-lib/pkgdown/issues/1618#issuecomment-831416962
=> autolink_bare_uris

NEWS.md, R/utils.r, tests/testthat/_snaps/build-search-docs/search.json, tests/testthat/assets/news/README.md, vignettes/test/rendering.Rmd
=> Fix the regex extracting the section level

NEWS.md, R/build-reference.R, R/context.R
=> avoid self-link even when @rdname was used

R/build-search-docs.R
I'm less sure this is the right thing to do.
=> Rm dev paths from production sitemap

DESCRIPTION, R/build-articles.R, R/build-news.R, R/build-reference.R, R/build-tutorials.R, R/build.r, man/build_articles.Rd, man/build_home.Rd, man/build_news.Rd, man/build_reference.Rd, man/build_search.Rd, man/build_site.Rd, man/build_tutorials.Rd, man/pkgdown-package.Rd, man/pkgdown_print.Rd, man/rmd-fragments/authors-configuration.Rmd, man/rmd-fragments/footer-configuration.Rmd, man/rmd-fragments/home-configuration.Rmd, man/rmd-fragments/navbar-configuration.Rmd, man/rmd-fragments/sidebar-configuration.Rmd, man/rmd-fragments/sidebar-sources.Rmd, man/test-links.Rd
Fix #1564
Note that the actual fix is https://github.com/r-lib/roxygen2/pull/1229/
=> add language info where it is missing

vignettes/metadata.Rmd
=> Make scope of data_open_graph() clearer

R/render.r
=> update file modification time even when the content is the same

R/html-tweak.R, R/render.r
=> Remove sidebar TOC when useless

R/context.R, R/init.R
Fix #1730
For real this time sorry, I got the levels wrong.
=> fix article index fix

R/build-search-docs.R, man/build_search.Rd
=> Add mention of pkgdown_sitrep() in build_search() docs

NEWS.md, R/package.r, tests/testthat/test-package.r
=> Only look for vignettes that are files

NEWS.md, inst/assets/BS3/pkgdown.css, inst/assets/BS4/pkgdown.css
=> Add pandoc reference styling

inst/assets/BS3/pkgdown.css, inst/assets/BS4/pkgdown.css, inst/assets/BS4/syntax-highlighting.css
This fixes the symptom of #1790 (and is a small but useful improvement) but doesn't fix the underlying cause.
=> Move height closer to max-width

tools/syntax-highlight.R
Please ignore this PR if the link was intentionally broken to preserve origin.
=> Update URL to KDE default styles reference

NEWS.md, R/build-articles.R, R/build-reference.R, R/test.R, R/utils.R, man/test-long-lines.Rd, pkgdown/_pkgdown.yml, tests/testthat/assets/articles/vignettes/width.Rmd, tests/testthat/test-build-articles.R, tests/testthat/test-build-reference.R, vignettes/test/rendering.Rmd
=> Set width in articles and examples

R/tweak-tabset.R, tests/testthat/_snaps/tweak-tabset.md
https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior
=> Update markup of BS5 tabs

R/build-reference-index.R, tests/testthat/test-build-reference-index.R
=> Don't keep duplicated entries in index page.

R/build-search-docs.R, R/highlight.R, R/test.R, R/tweak-reference.R, inst/BS3/templates/content-reference-topic.html, inst/BS5/templates/content-reference-topic.html, man/test-verbatim.Rd, tests/testthat/test-highlight.R, tests/testthat/test-tweak-reference.R
=> Improve handling of pre + div.sourceCode

NEWS.md, inst/BS5/templates/navbar.html, man/build_site.Rd, man/rmd-fragments/navbar-configuration.Rmd, vignettes/customise.Rmd
@maelle after implementing #1922, it suddenly occurred to me that we could just use `includes` for this. Maybe this is the simplest approach?
=> Add navbar includes

NEWS.md, R/build-reference-index.R, R/topics.R, tests/testthat/_snaps/build-reference-index.md
Fixes #1935
@maelle do you remember why the name column had such a complicated structure? I can't see any reasoning in #1664, and the extra layer of list-ness doesn't seem to be used anywhere.
=> Refine reference index section collation

DESCRIPTION
=> add bslib minimal version

R/build-home-md.R
=> Indicate what file is built for easier debugging if something goes wrong

.github/CONTRIBUTING.md
Cf #1987.
The info is in the code (:sweat_smile: ) and in the linking vignette at the moment, if I follow correctly.
=> Add info about public-facing metadata in CONTRIBUTING

NEWS.md, R/build-reference-index.R, pkgdown/_pkgdown.yml, tests/testthat/_snaps/build-reference-index.md, tests/testthat/test-build-reference-index.R
=> fix build_reference_index items checks

man/build_home.Rd, man/rmd-fragments/home-configuration.Rmd
=> do not escape init_site mention

R/build-redirects.R, tests/testthat/test-build-redirects.R
* Don't generate if no url
* Make error clear for redirects with no url
Fixes #1986
=> Improve article redirect handling

NEWS.md, R/tweak-reference.R, man/test-links.Rd, man/test-verbatim.Rd, tests/testthat/test-highlight.R
=> account for new roxygen2 output for generic code blocks

man/build_home.Rd, man/rmd-fragments/authors-configuration.Rmd
=> Clarify use of absolute URL in author config

R/rd-data.R, tests/testthat/test-rd-data.R
=> Don't prematurely drop whitespace in value  blocks

.github/workflows/no-pandoc.yaml
=> Restore no-pandoc action

NEWS.md, R/build-articles.R, R/build-reference-index.R, inst/BS3/templates/content-article-index.html, inst/BS3/templates/content-reference-index.html, inst/BS5/templates/content-article-index.html, inst/BS5/templates/content-reference-index.html, tests/testthat/test-build-reference-index.R
=> Use inline markdown for article/reference titles

NEWS.md, R/tweak-page.R, R/tweak-reference.R, tests/testthat/test-tweak-reference.R
=> Strip logo in ref-description

NEWS.md, R/build-reference-index.R, R/pkgdown.R, R/topics-external.R, R/topics.R, tests/testthat/_snaps/build-reference-index.md, tests/testthat/_snaps/topics-external.md, tests/testthat/_snaps/topics.md, tests/testthat/test-build-articles.R, tests/testthat/test-build-home.R, tests/testthat/test-build-reference-index.R, tests/testthat/test-build-reference.R, tests/testthat/test-topics-external.R
=> Add external topics to package topics

NEWS.md, R/topics-external.R, R/topics.R, tests/testthat/_snaps/topics-external.md, tests/testthat/_snaps/topics.md, tests/testthat/assets/reference/DESCRIPTION, tests/testthat/assets/reference/R/funs.R, tests/testthat/assets/reference/man/a.Rd, tests/testthat/assets/reference/man/b.Rd, tests/testthat/test-topics-external.R, tests/testthat/test-topics.R
=> Fix topic selection and thoroughly test

NEWS.md, R/build-articles.R, tests/testthat/test-build-articles.R
=> Ignore getting started when checking all articles are indexed

NEWS.md, inst/BS5/templates/head.html
Fix #2207 thanks to @GregorDeCillia
Fix #2208
Seeing https://rawgit.com/ makes me wonder why it used to work. :sweat_smile:
=> fix: CDN problem for bootstrap-toc

NEWS.md
=> Fix link to issue for ko translation

R/rd-example.R, tests/testthat/test-rd-example.R
=> Handle long `@examplesIf` conditions

.github/workflows/R-CMD-check.yaml, DESCRIPTION, tests/testthat/_snaps/rmarkdown.md
Locally I am seeing
```
testthat::snapshot_review('rmarkdown')
```
=> Pandoc + callr updates

R/tweak-homepage.R, tests/testthat/_snaps/tweak-homepage.md, tests/testthat/test-tweak-homepage.R
=> fix: badge removal from main content when custom sidebar

DESCRIPTION, R/build.R, man/build_home.Rd, man/build_site.Rd, man/rmd-fragments/home-configuration.Rmd, man/rmd-fragments/sidebar-configuration.Rmd, man/test-links.Rd
=> docs: treatment of badges in the sidebar depending on development mode

README.Rmd, README.md
=> docs: new link for usage

NEWS.md, R/package.R, tests/testthat/test-package.R
=> Sort articles alphabetically by file name

man/rmd-fragments/navbar-configuration.Rmd
See [`article_is_intro()` function](https://github.com/r-lib/pkgdown/blob/main/R/build-articles.R#L437-L440).
=> Mention necessary `.` -> `-` replacement for intro vignette

R/build-reference.R, R/build.R, R/rd-example.R
Separated from https://github.com/r-lib/pkgdown/pull/2294.
=> Cosmetic style fixes

NEWS.md, R/rd-html.R, tests/testthat/test-rd-html.R
And use HTML5. Fixes #2400.
Merge commit '6fc98fa6773df431471b2b28ba59361d647fafc2'
=> Remove duplicate `\cr` definition

NEWS.md, R/build-news.R, tests/testthat/_snaps/build-news.md, tests/testthat/test-build-news.R
=> Warn if no version headings found in NEWS.md

NEWS.md, inst/BS5/templates/content-article-index.html, inst/BS5/templates/content-reference-index.html
Fixes #2352
@gadenbuie how does this look?
=> Wrap section descriptions in `<div>`, not `<p>`

R/build-home-index.R, R/build-reference.R, R/rd-html.R, tests/testthat/_snaps/build-home-index.md, tests/testthat/_snaps/build-reference.md, tests/testthat/_snaps/rd-html.md
=> Unwrap remaining purrr errors

NEWS.md, inst/BS5/assets/pkgdown.scss
With styles inspired by @glin.
Fixes #2138
=> Add skip link styling

man/build_home.Rd, man/rmd-fragments/home-configuration.Rmd
=> No longer mention strip_header

R/check.R, man/check_pkgdown.Rd
=> Describe what check_pkgdown() actually does

NEWS.md, R/navbar.R, tests/testthat/_snaps/navbar.md, tests/testthat/test-navbar.R
=> Check navbar structure

vignettes/customise.Rmd
=> More info about making a template package

R/context.R, R/markdown.R
=> Finish off cli conversion

NEWS.md, R/build-articles.R
=> `input` is already a relative path

R/build-articles.R, R/build-home.R, R/build-news.R, R/build-reference.R, R/build-search-docs.R, R/build-tutorials.R, R/build.R, R/init.R, man/build_articles.Rd, man/build_home.Rd, man/build_news.Rd, man/build_reference.Rd, man/build_search.Rd, man/build_site.Rd, man/build_tutorials.Rd, man/init_site.Rd
=> Improve reference headings

NEWS.md, R/build-articles.R, man/build_articles.Rd, tests/testthat/_snaps/build-articles.md, tests/testthat/test-build-articles.R
=> Silently drop internal articles section

R/rmarkdown.R
Either my cli formatting skills are very outdated or there is a missing closing brace here.
If I'm right this is a super minimal typo, hopefully no need for a news entry... 😃
=> Fix typo in cli message

NEWS.md, inst/BS5/assets/pkgdown.scss
=> Tweak mobile navbar display

NEWS.md, R/rd-html.R, tests/testthat/_snaps/rd-html.md, tests/testthat/test-rd-html.R
=> Mimic tools:::htmlify()

R/build-favicons.R, R/build-home-index.R, R/build-home-md.R, R/build-logo.R, R/build-search-docs.R, R/check-built.R, R/config.R, R/context.R, R/deploy-site.R, R/init.R, R/pkgdown.R, R/render.R, R/utils-fs.R
=> Don't use `fs` where not needed

R/config.R, R/pkgdown.R
=> `_pkgdown.yaml` should be optional

R/check-built.R, tests/testthat/_snaps/build-articles.md
=> More info about how to fix alt-text

NEWS.md, R/build-articles.R, R/build-reference-index.R, R/usage.R, R/utils.R, tests/testthat/test-build-articles.R, tests/testthat/test-build-reference-index.R
=> Only add backticks to article/template names if needed

R/build-articles.R, R/figure.R, R/render.R
=> Use modify_list() everywhere

R/build-articles.R, R/rmarkdown.R, tests/testthat/_snaps/build-articles.md
* Improve `render_rmarkdown_style()`
* `build_articles_index()` now renders invisibly
* Fix incorrect call pass through
=> Minor article refactoring

inst/BS5/assets/pkgdown.scss
=> Use adaptive colour for homepage sidebar on mobile

R/render.R, inst/BS5/templates/head.html
@gadenbuie does this look good to you?
=> Tidy up open graph metadata in head.html

inst/BS5/assets/pkgdown.scss
Shifting from static SCSS variables to  dynamic CSS variables that respond when the mode changes
=> More dark mode tweaks

vignettes/customise.Rmd
Fixes #2560
@olivroy what do you think of this? In hindsight, I think this would be clearer if `template` was instead call `site` and `navbar` and `footer` were nested underneath it.
=> Clarify what's in the customise vignette and where else you should look

R/build-search-docs.R, R/development.R, R/figure.R, R/package.R, R/repo.R, tests/testthat/_snaps/development.md, tests/testthat/_snaps/package.md, tests/testthat/_snaps/render.md, tests/testthat/test-development.R, tests/testthat/test-package.R, tests/testthat/test-repo.R
Which also flowed through into as_pkgdown() and package_repo()
=> Update development.R to use modern error style

R/build-articles.R, R/build-reference-index.R, R/navbar.R, R/topics.R, tests/testthat/_snaps/topics.md, tests/testthat/test-topics.R
@maelle more passing of `pkg`!
=> Using standard error handling in select_topics()

tests/testthat/test-build-home-authors.R, tests/testthat/test-build-home-index.R, tests/testthat/test-build-home.R, tests/testthat/test-markdown.R, tests/testthat/test-package.R, tests/testthat/test-repo.R
=> Lint tests

DESCRIPTION
To ensure that all pkgdown users get the latest version
=> Bump downlit version

po/R-de.po
=> Update German translation

po/R-ca.po
=> Update Catalan translations

po/R-ca.po
As per https://github.com/r-lib/pkgdown/pull/2665#discussion_r1642402004, change strings to feminine gender form
=> Improve Catalan translations

.github/workflows/pkgdown.yaml
Includes tinytex to fix build errors
=> Use quarto action consistently

po/R-fr.po
For #2659.
@maelle or any other French speaking user of the package, please feel free to review and suggest edits. I would particularly like to know what you think about "superseded" and "experimental", should we write "remplacée" and "expérimentale" with their feminine style since it will most likely reference to a function (feminine word in French)?
@Hadley I did not compile the changes, I thought you would do it when the issue will be completely resolved.
=> Update fr translations for 2.0.9.9000

po/R-tr.po
Update Turkish translation, addresses #2659
=> Update Turkish translation

R/clean.R
Observed and tested in https://github.com/krlmlr/duckdbneo/.
=> Fix `deploy_to_branch()` for pristine repositories

NEWS.md, R/build-article.R, R/render.R, R/tweak-navbar.R, tests/testthat/test-build-article.R
=> Re-activate article navbar after building Rmd article

NEWS.md, R/build-news.R, tests/testthat/test-build-news.R
=> Safer unpacking of package timeline

po/R-fr.po
@jplecavalier Ici je dirais plutôt paquet mais je peux comprendre que ce soit une question de pays ?
=> paquetage -> paquet ?

DESCRIPTION, R/build.R, man/build_site.Rd
=> Update docs for branch setting

DESCRIPTION, NEWS.md
=> Depend on R version >= 4.0.0

NEWS.md, inst/BS5/assets/pkgdown.js
=> added keyboard shortcut to focus search"

R/rd-example.R
=> Use deparse1() instead of paste(deparse(), collapse = " ").

vignettes/customise.Rmd
Replaced 'Bootstwatch' with correct spelling 'Bootswatch'
=> Fixed 'Bootstwatch' typo in customise.Rmd

R/build-home-index.R
=> Fix error on missing bug reports

R/build-home-authors.R, tests/testthat/_snaps/build-home-authors.md, tests/testthat/test-build-home-authors.R
=> Fix yaml author block parsing

R/build-quarto-articles.R
=> Error if quarto with old bootstrap

R/build-quarto-articles.R
=> Delay check on bs version for building quarto articles

inst/BS5/assets/pkgdown.scss, tests/testthat/_snaps/init.md
=> Only hyphenate on small screens

DESCRIPTION, R/render.R, R/utils-io.R
=> Drop digest dependency

DESCRIPTION
=> Bump ragg requirement

NEWS.md, R/build-home-index.R, R/build-news.R, R/build.R, R/utils.R, man/build_site.Rd, tests/testthat/test-utils.R
=> Remove `pkgdown.internet` option

vignettes/how-to-update-released-site.Rmd
I actually needed to do this for usethis and I followed these instructions exactly. And I discovered some rough edges.
=> Fixup instructions for re-publishing a released site
