R/build.r
R/package.r
R/to-html.r
inst/templates/head.html

I have rebased my PR in #62  and #64. It allows customizing themes and bootstrap files, which enables me to use bootstrap 3 in my own package documentation: http://randy.city/iterpc/. It also allows me to show math in the documentations.

Customization of themes/ bootstrap and Adding Mathjax support

---

R/build.r
R/package.r
inst/templates/content-index.html

After merging #69, only a few changes are left as it addressed most of the issues I found.
You can have a look at results generated using the branch of this pull request under
http://kinfit.r-forge.r-project.org/gmkin_static/index.html
http://kinfit.r-forge.r-project.org/mkin_static/index.html
http://kinfit.r-forge.r-project.org/kinfit_static/index.html

Small documentation update, overwrite vignettes on copying and improve dependencies in index.html

---

README.md
inst/templates/footer.html

http://twitter.github.com/bootstrap/ works, http://twitter.github.com/bootstrap doesn't. I didn't update the URL to getbootstrap.com to reflect that an older version is used.

Fix broken Bootstrap redirect in template footer

---

DESCRIPTION
R/build.r
man/build_site.Rd

* `build_demos` now admits `.R` files as well as `.r`.
* `build_site` has individual flags for vignettes (`with_vignettes`), demos (`with_demos`) and readme (`with_readme`).

Admit .R extension and disable components selectively

---

R/build.r

Vignette outputs are removed in origin after being copied.

Remove generated .html under /vignettes

---

R/to-html.r
inst/templates/content-topic.html

- extract split_at_linebreaks()

Properly render multiline text in seealso sections

---

R/rd.r
R/to-html.r
tests/testthat/test-to_html.R

\eqn and \deqn have two formats: \eqn{latex}{ascii} and \eqn{latexascii}
they are correctly handled now
fix #101

	fix bug related to \eqn and \deqn

---

R/build-articles.R
R/build-reference.R
R/util.r

fixes #172 
Strangely PNGs generated from the render all have the format `README-chunk_label-number.png` (e.g., `README-plot-1.png`), despite the fact that many of the images don't come from a README per se.
I couldn't find where the `README` part is coming from; I presume this is a default on the `rmarkdown` side.
I think a better filename would be `pkg$vignettes$name-chunk_label-number.png`.

copy and build vignettes in docs/articles

---

R/build-home-authors.R

`given` can be a character vector, see [`?person`](https://www.rdocumentation.org/packages/utils/versions/3.3.1/topics/person).
@hadley: PTAL, can't build RSQLite docs without this.

Support multiple given names

---

inst/templates/content-reference-topic.html

Fixes #215
A similar problem presumably occurs with the html entities inserted
for the dQuote and sQuote tags in R/rd-html.R. As they can occur on many
occasions, the fix needs to be different.

Do not apply html escaping on function argument names

---

R/build-reference-index.R
vignettes/pkgdown.Rmd

Syntax example from RSQLite:
```yml
- title: Connection methods
contents:
- matches("^[^,]+,SQLiteConnection")
exclude:
- query-dep
```
Do we need to be able to exclude internal functions?
```yml
- title: Connection methods
contents:
- matches("^[^,]+,SQLiteConnection")
exclude:
- query-dep
- is_internal()
```

Support exclude for reference/title

---

R/build-news.R

From [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file): 
> The mandatory ‘Package’ field gives the name of the package. This should contain only (ASCII) letters, numbers and dot [...]

close #251: parse package names with alnum and dots

---

R/render.r

1. fix #208: in line 88 : 
2. mod in line 63: making the "params" of template section in yaml config worked properly, e.g. parameter *bootswatch*
```
template:
params:
bootswatch: cerulean
```

fix the render.r to enable  "template" section in _pkgdown.yml worked properly

---

vignettes/pkgdown.Rmd

I included a "fixes #xxx" comment because the narrow issue of documenting this behavior has been addressed. You may wish to re-open to keep a reminder of the underlying behavior.
If I should open a different issue elsewhere, I remain at your service.

Adds vignette caveat to articles' documentation

---

R/build-articles.R
R/build-home.R
R/build.r
man/build_articles.Rd
man/build_home.Rd
man/build_site.Rd

Hi, I got this error to build a site for my package:
```r
pkgdown::build_site()
#> ...snip...
#> Updating README.md
#> Quitting from lines 71-74 (README.Rmd) 
#>  Error in parse(text = x, srcfile = src) : 
#>   invalid multibyte character in parser at line 3
```
The [README.Rmd in my package](https://github.com/yutannihilation/estatapi/blob/master/README.Rmd) contains non-ASCII characters and its encoding is UTF-8. This is fine with macOS and Linux, but I'm using Windows, where default encoding is not UTF-8. I have to pass `encoding = "UTF-8"` to `rmarkdown::render()` to knit UTF-8 files.
This PR adds `encoding` argument to fix this issue.

pass encoding to rmarkdown::render()

---

inst/templates/content-reference-index.html

#297. By default [whisker](https://github.com/edwindj/whisker#note) applies `html` escaping on the generated text, and Ampersands (&)  will be escaped as \&amp; To prevent this use {{{variable}}} (triple) in stead of {{variable}}.

Not apply html escaping on the content-reference-index title

---

R/build-home.R
tests/testthat/test-build_home.R

Fixes #303 
Tested this fix with 3 different mirrors and they all worked: 
- cran <- as.list(getOption("source"))[["CRAN"]]
- cran <- "https://cran.usthb.dz/"
- cran <- "https://cran.cnr.berkeley.edu/"
Also tested it to build spark.rstudio.com and it  worked as well.

Changing arguments for available packages

---

inst/assets/pkgdown.css

Avoids images to overflow in the floating table of content
Before
After

Set img max-width to 100%

---

DESCRIPTION
R/build-logo.R

Magick can be painful to get installed when it isn’t easy to get the imagemagick Magick++ library installed. Since it is only used for favicon.ico creation, I've made magick an optional dependency, allowing me to use the rest of the package. 
This was useful to me personally, but I figured I'd send a pull request in case it was useful to others as well.

Make Magick an optional dependency

---

R/build-reference-index.R

Fixes Overzealous pruning of topics #373
These issues might also be related?
* Missing documentation when using dummy function to document s4 methods #395
* Certain functions don't appear in index #374
* Missing links to items in reference index #369
There's a problem with different definitions of `%||%`.
The rlang definition is `if (is_null(x)) y else x` but the previous "in-house" definition was `if (length(.x) > 0) .x else .y)`.
This line requires the length-based logic and it's where the link text is going missing, because right now we always take `section_topics$funs`:
https://github.com/hadley/pkgdown/blob/e2d1b6f662cf5c931522c125da4c4fafad972165/R/build-reference-index.R#L51
Whereas these lines require the null-based logic: …

Restore dummy objects in reference index; fixes #373

---

R/build-home.R

...so now we filter out site URL in `urls` vector (e.g., filter out "http://hadley.github.io/pkgdown/").

Capture repo URL and not site URL when creating github link (fixes #412)

---

R/util.r
man/rel_path.Rd
tests/testthat/test-util.R

Closes #409.
Also related to #307.
`normalizePath()` documentation says:
> On Windows it converts relative paths to absolute paths, converts short names for path elements to long names and ensures the separator is that specified by winslash. It will match paths case-insensitively and return the canonical case. UTF-8-encoded paths not valid in the current locale can be used.
So that's why `rel_path()` didn't work on Windows.
To fix this, I first normalize the path directory and the current directory. The difference between the two strings is the relative path, so I use string-replacement to extract it out. 
This function below illustrates what happens inside the function on Windows.
```r
windows_rel_path_demo <- function(path, base) {
if (is_absolute_path(path)) {
path
} else {
if (base != …
```

make rel_path() work on Windows

---

R/link-article-index.R
R/package.r

Addresses #440. Only the vignette-building functions are changed; no changes are necessary for, e.g., `index.rmd` to be recognized and take precedence over `README.md` (see the branch [rmd-extension-revert-test](https://github.com/corybrunson/pkgdown/tree/rmd-extension-revert-test) for illustration).

admit .rmd extension for vignettes

---

R/package.r
vignettes/pkgdown.Rmd

Concept taken from [bookdown](https://bookdown.org/yihui/bookdown/usage.html) which renders all `Rmd` files expect those starting with `_`. Such files can be used as child documents. See [inbo/INBOtheme](https://github.com/inbo/INBOtheme/commit/d9efda692538dd07992ea6047feedf315baa12e9) for an example.
Solves #463

ignore vignette files starting with '_'

---

R/build.r
R/render.r
R/util.r

closes #339 
As I explained in the issue, `render_page` write HTML page using `write_if_different` with `cat` function which use `getOption("encoding")`. 
When it is not UTF-8, it seems to cause some issues with reference page that are not write as UTF-8 but HTML page has a  `<meta charset="utf-8">` and is expecting UTF-8.
I fix the issue forcing UTF-8 writing for HTML page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hadley/pkgdown/362)

always write UTF8 file when render page

---

R/build-home.R
R/html.R
man/build_home.Rd

This adds "must not have text" as an additional constraint for has_badges, fixing first paragraphs with links but no other markup being mistaken for a list of badges.
A workable definition for the badges paragraph which doesn't look at the content itself should be "contains only images with links". To strictly check for this, something along these lines would be required in addition:
```
length(xml2::xml_children(badges)) > 0 &&
all(xml2::xml_name(xml2::xml_children(badges)) %in% "img")
```
which gets a bit unwieldy, and I can't think of a sensible case not already covered by the proposed version.

Improve detection of badges on homepage

---

docs/pkgdown.js
inst/assets/pkgdown.js

Srolling to the bottom on some pages causes the sidebar to disappear. This extra JS prevents it from disappearing.
Based on https://github.com/leafo/sticky-kit/issues/31#issuecomment-51740033
See the disappearing behavior at:
- https://rnabioco.github.io/valr/index.html
- http://usethis.r-lib.org/index.html

prevent sidebar from disappearing at page bottom

---

inst/assets/pkgdown.css
inst/assets/pkgdown.js
inst/templates/head.html

Hi,
This PR introduces a feature: "copy to clipboard" buttons are inserted in `<pre class="examples"></pre>` elements in reference pages.
A demo can be found here: 
https://rlesur.github.io/klippy/reference/klippy.html#examples
The copy button appears when the examples are hovered.
Romain

Add copy to clipboard buttons to examples in reference pages

---

R/link-href.R
tests/testthat/test-href.R

The autolinking feature is really great! One edge case I hit where it didn't work exactly as expected was when there were explicit references to the package itself. `vignette("my-vignette")` would correctly link to my-vignette in the pkgdown site, but `vignette("my-vignette", package="mypackage")` would link to a CRAN mirror as it would for any other non-local package.
This change adds a check in `href_topic_remote` and `href_article_remote`: if the given `package` is the same as what has been set by `scoped_package_context`, they call the `_local` function instead. So `vignette("my-vignette", package="mypackage")` will link to the pkgdown site itself, as will `mypackge::func`.
Obviously this isn't hugely important, but I have found some legitimate cases where the explicit …

Make local hrefs even when explicitly referencing local package

---

R/build-articles.R

`has_vignette()` would indicate whether there are any files in the vignettes folder. However, a package might well have vignettes but none of them in Rmd format, so none of them part of the `pkg$vignettes` tibble processed in `build_articles()`, which would subsequently fail from `data_articles_index()` trying to setup an index for `"All vignettes"` with contents `"``"`.

build_articles() no longer fails for a pkg with non-Rmd vignettes only

---

R/markdown.R
R/render.r
R/utils-io.R
tests/testthat/test-build_news.R
tests/testthat/test-open-graph.R

fixes #514 encoding issue
Following #362, there is still an encoding issue with `build_news` and `build_home`. They do not render properly when building site for a 📦 in french on a computer with french locale. 
After investigation, I found that `build_news` and `build_home` both parsed `.md`  file using an internal `markdown` function. It uses pandoc to convert markdown to html then makes changes in html using `xml2`, writes back the temp html file and then reads it line by line with `readLines` with no encoding provided.
However, `xml2::write_html` enforces UTF-8 (see [source](https://github.com/r-lib/xml2/blob/master/R/xml_write.R), so `readLines` should assume UTF-8 input, but its default param is `encoding = "unknown"` that I think assumes an encoding based on `Sys.getlocale()`. …

enforce UTF8 reading when internally writing to UTF-8

---

R/markdown.R
tests/testthat/home-empty-readme-md/DESCRIPTION
tests/testthat/test-build_home.R

solves #411 by providing an explicit error message if tweak_code fails due to existing but empty README.md 
I added a test case as well which I checked that failed before adding the new error message to code.

improve error message if build_site fails due to empty README.md (#411)

---

R/build-home-license.R

* Change Full license url from license.html ⇨ LICENSE.html.
* Fixes #557.

Fix "Full license" link.

---

R/build-home-authors.R

* Add style to orcid img inline when gen'd from `build-home-authors.R`
* Fixes #568 .

Add orcid re-sizing inline.

---

R/init.R

With the current arrangement, I get the following when providing a custom assets path (`pkgdown/assets/`) in `_pkgdown.yml`:
```r
pkgdown::init_site()
── Initialising site ──────────────────────────────────────────────────────────────────────────────────────
Copying  '../../1440p.sh' to '1440p.sh'
Copying  '../../autostart' to 'autostart'
Copying  '../../Boostnote' to 'Boostnote'
Copying  '../../Desktop' to 'Desktop'
Copying  '../../Documents' to 'Documents'
Copying  '../../Downloads' to 'Downloads'
Copying  '../../Dropbox' to 'Dropbox'
```
After switching the arguments in
https://github.com/r-lib/pkgdown/blob/e937c92cffd8afb0c98c67ff1a5450fe6419f09b/R/init.R#L41
to `path_rel(template$assets, pkg$src_path)`
everything works as expected:
```r
pkgdown::init_site()
── Initialising site …
```

init.R: Fix path_rel() for custom assets

---

R/package.r

For example, when you use `usethis::use_pkgdown()`, you get an empty YAML file.
In this case, `meta <- read_meta(pkg)` (https://github.com/r-lib/pkgdown/blob/master/R/package.r#L20) returns `NULL` but `meta <- utils::modifyList(meta, override)` is expecting a list.

Always return a list

---

R/github.R
tests/testthat/test-href.R

Rebuilding one of my sites with the latest `pkgdown` code, I noticed some warnings like this:
```
Reading 'man/teams.Rd'
Warning in if (grepl("^https?://", path)) { :
the condition has length > 1 and only the first element will be used
```
I tracked it down to `github_source()`, which based on its logic and function signature, expected only a single `path` passed to it, while the function that calls it passes in `paths`. The condition that triggered the warning was when an .Rd file was created by roxygen from multiple .R files. 
This patch vectorizes `github_source` so that the logic is correct and no warnings are emitted.

Fix warnings from github_source()

---

inst/assets/pkgdown.css

The new docsearch is really great! I added it to http://crunch.io/r/crunch/, and then I noticed that if I search for something that has a lot of hits, or if the results are wordy, the dropdown that appears can spill off the page and it doesn't scroll:
Adding this CSS lets the dropdown scroll if necessary:

Let search results scroll

---

vignettes/test/jss.Rmd

eliminates this warning to during pkgdown build:
```
[WARNING] This document format requires a nonempty <title> element.
Please specify either 'title' or 'pagetitle' in the metadata.
Falling back to 'file14a8921c4b6df.utf8'
```

add pagetitle to suppress build warning

---

NEWS.md
R/link-href.R
R/utils.r
tests/testthat/test-utils.R

We cannot take the package name from the
environment of the function in this case,
but need to look at the import env of the package.
Fixes #666.

Fix re-exporting non-function object

---

NEWS.md
R/build-news.R
inst/templates/content-news-index.html
tests/testthat/assets/news-multi-page/DESCRIPTION
tests/testthat/assets/news-multi-page/NEWS.md
tests/testthat/assets/news-multi-page/_pkgdown.yml
tests/testthat/test-build-news.R

Multi-page news rendering was broken; setting `news: one_page: false` was having no effect. 
Not sure what you want the index to look like, this just makes it a simple list with links:
<h1>Release notes</h1>
<ul>
<li> Version 2.0
<li> Version 1.0
</ul>

fix multi-page news rendering

---

NEWS.md
docs/pkgdown.js
inst/assets/pkgdown.js

Mark a single tab as active, by looking for the longest match to the path components. If there are multiple matches with equal length, the left-most will be highlighted.
Fixes #660

Improve active nav algorithm

---

DESCRIPTION
NEWS.md
R/init.R
man/init_site.Rd
tests/testthat/test-build_home.R

pkgdown does not currently build-ignore the files it creates, causing a NOTE during R CMD CHECK.
`init_site()` now calls `usethis::use_pkgdown()` to add `docs/` and `_pkgdown.yml` to `.Rbuildignore`.
Need to add news bullet once 1.1.0 is released.
Part of #709

Build-ignore pkgdown infra during init

---

R/build.r
docs/reference/build_site.html
man/build_site.Rd

Hi!
This PR contains a quick commit that adds the missing https header of some urls in build_site documentation.
That `\url{rdocumentation.org}` took me to <http://pkgdown.r-lib.org/reference/rdocumentation.org> instead of <https://rdocumentation.org>.  This PR would fix it.  Thanks.

fix urls in build_site docs

---

R/rd-html.R
tests/testthat/test-rd-html.R

Sexpr with multiple args like `\Sexpr[results=rd,stage=build]` were not parsed correctly. Changing commas to semicolons (i.e., `results=rd;stage=build`) enables `rlang::parse_exprs()` to parse multiple args.
Closes #720

Process multiple args in \Sexpr{}

---

NEWS.md
R/build-home-index.R
R/build-home.R
R/build-news.R
R/utils.r
man/build_home.Rd
tests/testthat/test-utils.R

Closes #773. Closes #762. Closes #766.

Provide option to disable internet connections

---

R/build-logo.R

Was looking at this because it's awesome (especially with `usethis::use_logo`!).
Typo + I find "Magick" misleading. I was wondering whether it should actually be "The magick package" to make it clearer?

Correct message

---

NEWS.md
R/build-cname.R
R/init.R
tests/testthat/assets/cname/DESCRIPTION
tests/testthat/assets/cname/_pkgdown.yml
tests/testthat/test-build-cname.R

This will automatically create a CNAME file if there is a url entry in the metadata.
This is useful in conjunction with #792, as in that scenario there is no existing CNAME file that can be re-used.
It also avoids needing to create this by hand, which is something I tend to forget to do.

Add a CNAME file if the site has a url entry in the metadata

---

R/build-cname.R

CNAME files cannot have comments, so we need to disable the check for a
pkgdown generated file.
Fixes #799

Fix build_cname() to no longer check for a pkgdown comment

---

NEWS.md
R/build.r

The colored diagnostic messages are lost when running in a separate
child process unless you tell the child process that it can display
color. We do that by passing the color settings of the parent process
down to the child.

Retain colored output even when executing in a new process

---

R/deploy-site.R
man/deploy_site_github.Rd

After seeing how `vctrs` auto deploys `pkgdown` with travis, and after playing around with it myself, I think `skip_cleanup: true` needs to be added to the `.travis.yml` to keep the built R package around.
Otherwise you get:
https://travis-ci.org/tidymodels/yardstick/builds/433582268#L1306
I think this is because travis has cleaned up the directory after the build.

Add skip_cleanup to deploy_site_github() docs

---

NEWS.md
R/build-articles.R
man/build_articles.Rd

Configure vignette toc depth

---

inst/templates/head.html

The R Studio mirror is reported to have only intermittent connectivity in China.
Part of #785

Use higher availability CDN for Mathjax

---

R/build-home-authors.R
R/build.r

https://tidyverse.org/rstudio-logo.svg returns `HTTP 301` and redirects to https://www.tidyverse.org/rstudio-logo.svg
The page loading time is affected by this because the DNS resolution and the TLS handshake now need to be performed twice (first for `tidyverse.org` and then for `www.tidyverse.org`).
This PR updates the path of `rstudio-logo.svg` to bypass the `HTTP 301` response.

Edit rstudio-logo location to bypass HTTP 301

---

NEWS.md
R/build-home-index.R

Fixes #855.
This implements the defensive approach of not including any link for bug reports in the sidebar if the DESCRIPTION does not have a BugReports field.

omit link (to NA) if there is no BugReports field

---

NEWS.md
R/build.r

This fixes #861 by passing the option `pkgdown.internet` that could be set by the user to `build_site_external` call to `callr::r()`. It completes #774.
This now works:
```r
options(pkgdown.internet = FALSE)
pkgdown::build_site()
```
I did not look yet if I should add a test for `build_site_external`.

pass pkgdown.internet option in build_site_external

---

R/build-home.R
R/build.r
man/build_home.Rd
man/build_site.Rd

This follows #877 and complete #774 
* Section moved to `build_site` help page
* add some warning about the option `pkdown.internet = FALSE` not being useful if the 📦 for which pkgdown is used for requires internet in examples and vignette.

move and complete help section about disable internet connection feature

---

R/build-news.R
R/github.R
R/link-href.R
inst/templates/footer.html

Default to HTTPS for:
- rdocumentation.org (301 redirects to HTTPS)
- pkgdown.r-lib.org (301 redirects to HTTPS)
- github.org (301 redirects to HTTPS)
- crandb.r-pkg.org (supports HTTPS but no redirect)

Default to HTTPS

---

NEWS.md
inst/templates/docsearch.html
inst/templates/head.html
vignettes/test/mathjax.Rmd

It should be more efficient to load all resources from a single CDN because DNS resolution, TLS handshake, etc. only need to be performed once.
I picked cloudflare because it looks like it was already providing the largest number of external resources.
Also, as cool side effects:
- SRI hashes has been added in places they were previously missing, thus increasing security
- Font Awesome has been updated from 4.6.3 to 4.7.0. Font Awesome 5.0+ should also be soon available and I can submit a PR with this change later.
- Docsearch resources have been updated as well.
I tested the changes locally and everything seems to work fine
TODO:

Fetch all resources from a single CDN

---

NEWS.md
inst/templates/content-home.html

Hide sidebar on mobile home pages.

---

NEWS.md

'longer' was originally there: https://github.com/r-lib/pkgdown/commit/18e30a57aa7781808cb2cc18c6bae855201de9bb#diff-8312ad0561ef661716b48d09478362f3R3
but was then removed: https://github.com/r-lib/pkgdown/commit/169cb82716652f95b26660e505362e486d8dbebc#diff-8312ad0561ef661716b48d09478362f3R54

replace 'longer'

---

NEWS.md
R/deploy-site.R

This PR allows parameters to be passed from `deploy_site_github()` to `build_site()`, which is the documented behavior but is not implemented.

Pass params from deploy_site_github to build_site

---

vignettes/pkgdown.Rmd

`URL` belongs to the second enum item.

Reorder publication targets

---

R/build.r

this is just what appears to be a small typo in the usage example.
Using 
```
development:
mode: development
```
as documented yields:
```
Error: development$mode` in `_pkgdown.yml must be one of auto, release, devel, or unreleaed
```
So it's gotta be `"devel"`.

fix usage example development -> devel

---

NEWS.md
R/rd-html.R
tests/testthat/test-rd-html.R

- Tables with tailing TEXT (such as \n) now do not contain extra last rows
- Empty separator detection is row robust to other separators (such as \code{})
Resolves #928

Fixed malformed tables

---

NEWS.md
R/build.r
R/navbar.R
inst/assets/pkgdown.css
inst/templates/head.html
man/build_site.Rd
vignettes/pkgdown.Rmd

fontawesome deprecated the fa prefix in version 5. now using the fas and fab (for brands) prefixes.
Closes #953

Update fontawesome to 5.7.1

---

R/build-tutorials.R
R/link-article-index.R
R/package.r
R/utils-fs.R
tests/testthat/test-build_article.R
tests/testthat/test-figure.R

Breaking change in fs 1.3.0, see https://fs.r-lib.org/news/index.html
This change will be invisible to end users, should I add a bullet point to the changelog nonetheless?

Update dir_ls recursive arg to recurse

---

R/deploy-site.R
man/deploy_site_github.Rd

This closes #1021 and possibly #994 
Two improvements suggested, easily reversible
* use `before_cache` instead of `before_deploy` as [adviced](https://github.com/r-lib/usethis/issues/747#issuecomment-489772348)
* Suggest to use `usethis::use_pkgdown_travis()` for a quick setup to help with the step describe
Another choice could be to rewrite this doc to guide as first choice to `usethis::use_pkgdown_travis()` for setup and detail the step to configure here or there.

improve deploy doc

---

NEWS.md
inst/assets/pkgdown.css
inst/assets/pkgdown.js
inst/templates/head.html

See https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects
Not entirely sure I did everything right so feel free to test more before merging (I will do the same on my end).

Implement sticky navbar in css

---

DESCRIPTION
NEWS.md
R/build-home-index.R
R/build-home.R
R/build-reference.R
R/build.r
R/deploy-site.R
man/build_home.Rd
man/build_reference.Rd
man/build_site.Rd
tests/testthat/test-build_home.R
tests/testthat/test-figure.R

Rework as [discussed in #1020](https://github.com/r-lib/pkgdown/pull/1020#issuecomment-492212317). 
Hadley said: I think this should optional, and controlled by an argument that also controls whether or not document() is run — i.e. we need something like development = FALSE which would:
- in build_site(), error if the package is not installed
- in build_reference(), skip document() and use library() instead of pkgload
- in build_home(), never rebuild README.md from README.Rmd

Add 'devel' parameter

---

R/build.r
man/build_site.Rd

This PR adds two sentences to the section of the `build_site()` documentation to suggest developers be cognizant of their responsibilities for collection and disclosure when using Google Analytics.
The wording is intentionally high-level to stay succinct and avoid going stale. Hopefully, it is not too vague to be useful.
Closes #1009.

Updated build docs with caution on Google Analytics

---

R/build.r
man/build_site.Rd
tests/testthat/test-development.R

Clarify boundary between unreleased and release in tests

---

NEWS.md
R/build-news.R
tests/testthat/test-build-news.R

Included a decent amount of refactoring, first to make the regular expression more readable, and then to make news_version return something that was easier to test.
Fixes #980

Increase flexibility of news title matching

---

inst/assets/pkgdown.css
inst/assets/pkgdown.js
inst/templates/navbar.html

For both the tidytemplate and the rotemplate packages there are issues where the navbar overlaps the page body on small screens (https://github.com/tidyverse/tidytemplate/issues/42, https://github.com/ropensci/rotemplate/issues/15). 
In principle, this problem also exists with the default pkgdown theme, though not as often, because of the smaller navbar font size. Here are two examples [in the wild](https://radiant-rstats.github.io/radiant.multivariate/):
This can be fixed if the top-padding of the body is set relative to the navbar, see [this answer on SO](https://stackoverflow.com/a/20197508/2114932), which this PR draws upon.
My knowledge of Javascript and CSS is extremely limited, so it's quite likely that this PR can be improved upon, hence my labelling it as proof-of-concept. 
With …

Adjust padding-top based on navbar height

---

R/build-articles.R
man/build_articles.Rd
vignettes/pkgdown.Rmd

It took me a while to understand why my Rmarkdown files in `vignettes/tutorials/` were not included by `build_articles()`, because the documentation said: "pkgdown will automatically build all .Rmd vignettes, including those in subdirectories. The only exception are .Rmd vignettes that start with _". This pull request fixes that documentation.

Document exclusion of `vignettes/tutorials/` when building articles

---

R/metadata.R

rOpenSci is an example of an organization where each repository in the github org maps to a known pkgdown URL. This adds a special case to the auto-linking to make sure this known URL is checked.

Add special case for auto-linking rOpenSci docs.

---

R/render.r

See issue #1129 for details. 
Basically the `{{root}}` variable is always interpolated with a number of `../../../` to get to the root of the site. However the `404.html` is special because it may appear at any level.

Use full URL in 404 sites, fixes #1129

---

R/init.R

Favicons are currently only copied if they have been just created on the fly. This is a problem for repositories where the gh-pages branch is re-created as new orphan branch on deploy.
This PR solves this by always copying existing favicons.

Copy existing favicons

---

NEWS.md
R/build-home-authors.R
inst/assets/pkgdown.css
inst/templates/head.html

This prevents a request to a third party, thereby improving privacy, speed and robustness of pkgdown websites.
This is now possible thanks to https://github.com/FortAwesome/Font-Awesome/issues/4401.

Use ORCiD logo from FontAwesome 5.11

---

NEWS.md
R/deploy-site.R
man/deploy_site_github.Rd

`deploy_site_github()` does not currently support enterprise github for deployment and defaults to github.com. This is hardcoded in the `github_clone()` function. 
The proposal in this PR is to add a new argument `host` that would allow enterprise users to specify the URL of their github instance when deploying with Travis. I can confirm that this approach works for my org's internal github. 
Happy to provide any additional information.

Enable deploy_site_github() to handle GH enterprise instances

---

R/markdown.R

See https://github.com/r-lib/pkgdown/issues/1150#issuecomment-562948777
This PR adds two pandoc extensions. From [pandoc manual](https://pandoc.org/MANUAL.html#extensions):
- Extension: `tex_math_dollars`. Anything between two `$` characters will be treated as TeX math. The opening `$` must have a non-space character immediately to its right, while the closing `$` must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, $20,000 and $30,000 won’t parse as math. If for some reason you need to enclose text in literal `$` characters, backslash-escape them and they won’t be treated as math delimiters.
- Extension: `tex_math_single_backslash`. Causes anything between `\(` and `\)` to be interpreted as inline TeX math, and anything between …

Add math extensions for markdown parsing

---

NEWS.md
R/build-home-index.R

First brought up in #1031. This pull requests adds support for index files in the `pkgdown/` folder and I did add support for `pkgdown/index.md` for consistency. In the original issue I only mentioned `index.Rmd`.
I elected to put the `pkgdown/` specific files ahead of the other possible index and README files. My assumption: someone who creates `pkgdown/index.[R]?md` wants to use that file over any other.

Support `pkgdown/index.md` and `pkgdown/index.Rmd`

---

NEWS.md
R/markdown.R
tests/testthat/assets/markdown-dialect/DESCRIPTION
tests/testthat/assets/markdown-dialect/README.md
tests/testthat/test-amarkdown-dialect.R

This is the default (and recommended) markdown dialect as of pandoc 2.0
See https://pandoc.org/MANUAL.html
This fixes some problems we have where the pkgdown markdown is rendered differently from rmarkdown or github.

Use the recommended gfm markdown dialect

---

R/render.r

Instead of always assuming the filename "logo.png", actually use whatever `find_logo()` detects.

Fix logo uri in og:image defaulting to "logo.png"

---

R/html-tweak.R

Apparently the div was renamed throughout the package from `sidebar` to `pkgdown-sidebar` at some time.
fixes #1207

Fix badges not showing in dev section of sidebar

---

R/deploy-site.R
man/deploy_to_branch.Rd

Previously `deploy_to_branch()` would fail if the branch you were
deploying to did not exist on the remote. This fixes the issue by
creating a new orphan branch and pushing it to the remote if it does not
already exist.
Fixes #1223

Support deploying even if the branch does not exist.

---

inst/templates/config-docsearch.json

See https://github.com/algolia/docsearch-scraper/pull/423#discussion_r241115308.

Remove unused (and typoed) selector from docsearch json template

---

NEWS.md
R/build-home.R
R/html-tweak.R
man/build_home.Rd
tests/testthat/test-html-tweak.R

If the user puts the badges comments or an element with `id=badges`, I assume they want to extract the badges from there instead of having everything silently ignored.
This changes the detection code so that it extracts all badge-like links
1. between a pair of `badges: start` and `badges: end` comments
2. inside of an element with `id=badges` (not just divs, an ul would work too)
2. in the first paragraph, provided that paragraph only contains badge-like links (old logic)
This allows extraction of badges under more circumstances like e.g. from my package, where two badges look identical and have some explaining text:
> ```markdown
> 
> builds
> ------
> 
> - [![Travis](https://travis...)](https://travis...) – Travis
> - [![Bioconductor stable](https://bioc...)](https://bioc...) – …
```

Allow more way to specify badges

---

R/build-home-citation.R
tests/testthat/test-build-citation-authors.R

Since the previous line re-encode if already set and UTF-8 is a reasonable default.
Fixes #975

Declare encoding of citation as UTF-8

---

R/rd-html.R
R/test.R
inst/assets/pkgdown.css
man/test-lists.Rd
tests/testthat/test-rd-html.R

Fixes #786
Rendering of `test-lists`:

Tweak dl styling

---

R/build-home-citation.R

generate html style bib if no textVersion field in citation, fixes #1265

---

R/deploy-site.R

Travis-CI uses a shallow clone of the repository, which means that the
'origin' remote only tracks the HEAD branch. Even if we later fetch a
different branch the worktree command will still fail, because the
branch is not tracked by the remote. Using `git set-branches` we can
explicitly add the branch we are trying to deploy to be tracked by the
remote, which fixes the issue.
Fixes #1271

Explicitly set the remote's branch before fetching

---

NEWS.md
R/highlight.r
tests/testthat/test-highlight.R

Fix syntax highlighting on windows

---

R/build.r
man/build_site.Rd

I was super bone-headed yesterday and placed `components` at the toplevel of my YAML, even though it clearly says in the text that `structure` and `components` are nested under `navbar`.
Perhaps this can save other people from themselves.

disambiguate yaml nesting

---

R/build-reference.R
man/build_reference.Rd

this was clarified in https://github.com/r-lib/pkgdown/issues/954, thought it might be helpful for users expecting some selector for `@family`.

document that has_concept() covers @family tags

---

R/highlight.r
tests/testthat/test-highlight.R

This will prevent highlight markup from being stripped from code that consists entirely
of code comments (only lines beginning with #'s).
A partial fix for https://github.com/r-lib/pkgdown/issues/1296, but would still not syntax highlight code chunks that resulted in syntax
errors (e.g., when chunk options `collapse = TRUE` and `comment = NA`)

Allow highlighting of empty expressions

---

R/rd-html.R
tests/testthat/test-rd-html.R

015f5f56d842a45094beda9bb8d40b2b8f79fc9b introduced a typo into the `<dl>` header, which causes subsequent blocks to be absorbed into the `<dl>` by some rendering engines (e.g. Chrome’s). In most (all?) cases this luckily only causes subtle spacing issues.

Fix typo in <dl> header

---

inst/assets/pkgdown.css

There could be a rendering issue if the first column of the reference page is too narrow. For example,
This PR makes sure that each column has at least some minimum width so the table will be rendered nicely.

set a min-width of the reference table

---

R/highlight.r
tests/testthat/test-highlight.R

Improved version of #1307 accounting for problems caused by empty expressions consisting of empty strings or whitespace only.
Prevents highlight markup from being stripped from code that consists entirely of code comments (only lines beginning with #'s).
A partial fix for #1296, but would still not syntax highlight code chunks that resulted in syntax
errors (e.g., when knitr chunk options collapse = TRUE and comment = NA are set)

Allow highlighting of some empty expressions

---

NEWS.md
R/build-favicons.R
R/build-home-index.R
R/build-news.R
R/metadata.R

Thanks for for this awesome project!
In this PR, I'd like to propose swapping out calls to `httr::<verb>()` etc. with `httr::RETRY()`. This will make the package more resilient to transient problems like brief network outages or periods where the service(s) it hits are overwhelmed. In my experience, using retry logic almost always improves the user experience with HTTP clients.
I'm working on https://github.com/chircollab/chircollab20/issues/1 as part of Chicago R Collab, an R 'unconference' in Chicago.

use RETRY logic for HTTP calls

---

NEWS.md
R/markdown.R
tests/testthat/assets/readme-with-attr.md
tests/testthat/test-build-home-index.R
tests/testthat/test-markdown.R

Thanks for all the great work on `pkgdown` it's really fantastic. 
When building a site I noticed that building my index from `readme.md`, `index.md`, etc. wasn't catching and interpreting [header attributes](https://pandoc.org/MANUAL.html#extension-header_attributes) like `rmarkdown` does when rendering vignettes. It looks like this is because the flavor `markdwn_github` doesn't have the extension `header_attributes` on by default (since github doesn't strictly implement that itself). This adds that extension so that pkgdown rendered pages will use so that custom classes, ids, and attributes can be specified in a similar way that they can in vignettes.
This might be better as an optional parameter in case anyone was relying on rendering unescaped curly-brackets in headers.

Add header_attributes to markdown extensions

---

R/rd-example.R
R/test.R
man/test-dont.Rd
tests/testthat/test-rd-example.R

Unfortunately we need to parse and transform the Rd, so it is not completely trivial. This seems unavoidable.
If the condition is met, then the condition is not shown at all, and the code runs. 
If the condition is not met, then it is replaced by `if (FALSE)`, so the example code does not run. We can probably improve this.

Support @examplesIf roxygen tag, conditional examples

---

NEWS.md
R/build-articles.R

This PR internally sets `html_document(anchor_sections = FALSE)` to remove needless JS dependency.
Recently, `html_document` gained the `anchor_sections` argument, whose default is `TRUE`.
It adds a JavaScript dependency to anchor sections.
Although it becomes quiet when the document already anchor sections by themselves,
it still adds needless dependencies.

Set html_document(anchor_sections = FALSE)

---

R/markdown.R

Relates to #1470, which I'm also seeing
The "markdown_github" variant was deprecated in pandoc 2.0 (2017-10-29), although the significance of this seems to be changing, i.e. its use is causing more and more friction. Which makes sense.
In addition to switching to "gfm", I have brutally removed various incompatible extensions, some of which may have been load-bearing. Indeed I can't pass tests locally with this branch, so I expect to see CI failure. But I think this is indicative of a change that needs to happen.
*I get a clean pkgdown build for reprex, FWIW, when I install this PR. The `Deprecated: markdown_github. Use gfm instead.` warnings go away and there are no obvious deficiencies with the site.*

Stop using the deprecated 'markdown_github' variant

---

R/build.r
man/build_site.Rd
man/deploy_site_github.Rd

I was testing out the example displayed in section "YAML config - navbar" in build_site() reference page (https://pkgdown.r-lib.org/reference/build_site.html). I got an error when I blindly copied the example and executed it on my computer. Later I found the cause to be a missing colon in one key-value pair, which is in line 167 column 17 in https://github.com/r-lib/pkgdown/edit/master/R/build.r .
I realized that its just a typo on the webpage, rather than a bug in code - perhaps that's why none of the GitHub actions are able to detect this typo.

Fix Typo - Missing ":" - Line 167:17 - build.R

---

vignettes/metadata.Rmd

Google Structured Data Testing Tool is deprecated, and Google now recommends Google Rich Results Test instead.

updating opg-validator link

---

R/build.r
man/build_site.Rd

A proposition following issue #1465 .  
This aims to write in the documentation the values that `mode` can take in `_pkgdown.yml` before facing an error.

Update documentation: devel mode confusing

---

NEWS.md
R/utils.r

I first thought that this kind of thing was now done [cli](https://github.com/r-lib/cli)s job, but that had just been removed in https://github.com/r-lib/pkgdown/commit/77f909b0138a1d7191ad9bb3cf95e78d8e8d93b9, so here's a small fix.
This can be tested with
```r
pkgdown:::rule(paste0(rep(LETTERS, 4), collapse = "")) 
```
which should fail on pretty much any terminal width.
Since this isn't an exported function, I did not add a test.

protect CLI rule against narrow terminals closes #1435

---

vignettes/metadata.Rmd

or maybe it's only necessary if src is not an URL, actually

add other URL hint in metadata vignette

---

NEWS.md
R/init.R
R/render.r
R/utils-fs.R

Fix #1496
Cc @apreshill @cderv, I am sorry for this oversight.
The other method for overriding templates (having some folder and providing its `path` in the config file) still works.

Fall back on the bare templates directory in template packages

---

NEWS.md
R/build-home-index.R
R/build-home.R
man/build_home.Rd
tests/testthat/_snaps/build-home-community.md
tests/testthat/_snaps/data_home_sidebar.md
tests/testthat/test-build-home-community.R
tests/testthat/test-data_home_sidebar.R

Here's how it looks like for a structure `[links, license, readme, dev]`

Add TOC feature for the home sidebar

---

R/build-home.R
man/build_home.Rd
man/pkgdown-package.Rd

`pkgdown/index.md` is recognized and not `_pkgdown/index.md`
https://github.com/r-lib/pkgdown/blob/d34ce5fc8317e409437c502e8af3c2bca2b894c3/R/build-home-index.R#L4-L9
cc @apreshill

fix doc for build_home() and pkgdown/index.md

---

R/build-reference.R
man/build_reference.Rd
man/deploy_site_github.Rd

Fix issue #1504, the extra backtick in `build_reference` documentation.

Fix issue #1504

---

NEWS.md
R/build-reference-index.R
R/build.r
R/navbar.R
man/build_site.Rd
tests/testthat/_snaps/navbar.md
tests/testthat/assets/news-multi-page/DESCRIPTION
tests/testthat/test-navbar.R

Not too sure throwing a warning is actually a good idea. :thinking_face:

Support removing components from the navbar

---

NEWS.md
R/build.r
R/repo.R
man/build_site.Rd
tests/testthat/test-repo.R

The automatic github issue linking in pkgdown is really great. For projects that use jira (e.g. [the apache arrow project](https://issues.apache.org/jira/projects/ARROW/issues/ARROW-6103?filter=allopenissues)) it would be really great to be able to auto-link those issues as well.
This PR implements that autolinking by a package developer supplying a `jira_projects` item as well as a custom `issue` URL in the `repo` field of the _pkgdown.yml. Only when both of those are present does it add a regex like the github issues regex, but for the project names specified.
If this approach is acceptable, I'm happy to also add documentation explaining this setup in the appropriate place. 
Thanks for all of the awesomeness that is pkgdown.

Add ability to autolink to Jira issues

---

R/usage.R
tests/testthat/test-rd-html.R
tests/testthat/test-usage.R

I get the warning below for `rgl`, caused by man page https://github.com/dmurdoch/rgl/blob/master/man/persp3d.function.Rd :
```
> pkgdown::build_reference_index()
Warning: Failed to parse usage:
S3method(`persp3d`, function)(x, 
xlim = c(0, 1), ylim = c(0, 1), 
slim = NULL, tlim = NULL, 
n = 101, 
xvals = seq.int(min(xlim), max(xlim), length.out = n[1]), 
yvals = seq.int(min(ylim), max(ylim), length.out = n[2]), 
svals = seq.int(min(slim), max(slim), length.out = n[1]), 
tvals = seq.int(min(tlim), max(tlim), length.out = n[2]), 
xlab, ylab, zlab, 
col = "gray", otherargs = list(), 
normal = NULL, texcoords = NULL, ...)
S3method(`plot3d`, function)(x, ...)
```
The problem is that "function" is legal as a class name, but not in the expression `S3method(`plot3d`, function)(x, ...)` produced …

Methods can be put on class "function".

---

R/html-tweak.R

Due to
``` r
header <- xml2::xml_missing()
paste0("ok", header)
#> [1] "okNA"
sprintf("ok%s", header)
#> character(0)
```
<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

fix bug appearing when BS = 4 and no header

---

.github/workflows/pkgdown.yaml
DESCRIPTION

Add usethis as Config/Needs/website dependency

---

NEWS.md
R/context.R

Fix #1576 
The `topic_index` is documented here:  https://github.com/r-lib/downlit/blob/e22f072cfeaf91fbe7c38aeabd351aaa184d36fd/R/topic-index.R#L2, to map "aliases to Rd file names (sans extension)".  The `\name{}` field can differ, so it shouldn't be used here. 
This fixes https://github.com/r-lib/downlit/issues/83 .

The `\name{}` field in an Rd file shouldn't be used in the topic index

---

NEWS.md
R/html-tweak.R
tests/testthat/test-html-tweak.R

#1174 had introduced a regression.
The test case that had been removed
```html
<p><a href="https://travis-ci.org/thisisatest/thisisatest"><img src="https://travis-ci.org/thisisatest/thisisatest.svg?branch=master" alt="Linux Build Status"></a> </p>
```
has the second comment inside the paragraph which is what happens in quite a few packages out there.
For rOpenSci packages (cc @jeroen) badges were never detected even when the README had no one-liner quote because the first paragraph returned by `xml2::xml_find_first(html, "//p")` was a Matomo tracking image.

Fix badge regression

---

R/build-home-index.R
inst/assets/BS4/pkgdown.js
inst/templates/BS4/content-article.html
inst/templates/BS4/content-news.html
inst/templates/BS4/content-reference-index.html
inst/templates/BS4/content-reference-topic.html
inst/templates/BS4/content-title-body.html
tests/testthat/_snaps/data_home_sidebar.md

Fix #1583
Now to customize the depth of the TOC cf #1357 bootstrap-toc only supports two levels anyway. https://github.com/afeld/bootstrap-toc/issues/27

Exclude h1 from TOC

---

NEWS.md
R/context.R

Fixes r-lib/downlit#74
This is already documented in downlit, so I'm pretty sure it's a pkgdown issue.

Topic index should be a character vector

---

NEWS.md
inst/assets/BS3/pkgdown.css
inst/assets/BS4/syntax-highlighting.css

Reduce styling to allow the package to style as needed.
@maelle where does the corresponding code for BS4 live?

Align message/warning/error styling

---

NEWS.md
R/build-404.R
R/build-home-md.R
R/html-tweak.R
R/init.R
R/render.r
tests/testthat/_snaps/html-tweak.md
tests/testthat/test-html-tweak.R

Fix #1534, follow-up to #1524
I also noticed the link to the pkgdown stylesheet and JS was an absolute URL to the production stylesheet and JS, which is why https://pkgdown.r-lib.org/dev/404.html does not look good (only page linked from nowhere, which is why I missed it :upside_down_face: ).
The path to the logo also needs to be absolute on the 404 page.

fix 404 navbar and CSS

---

R/build-search-docs.R
tests/testthat/_snaps/build-search-docs/search.json

Fix #1656 
``` r
all <- function(...) {
not <- sprintf("[not(%s)]", paste0(paste0("descendant::", c(...)), collapse = "|"))
paste0(".//", c(...), not, collapse = "|")
}
all("p", "li", "caption", "figcaption", "dt", "dd", "blockquote", "div[contains(@class, 'line-block')]")
#> [1] ".//p[not(descendant::p|descendant::li|descendant::caption|descendant::figcaption|descendant::dt|descendant::dd|descendant::blockquote|descendant::div[contains(@class, 'line-block')])]|.//li[not(descendant::p|descendant::li|descendant::caption|descendant::figcaption|descendant::dt|descendant::dd|descendant::blockquote|descendant::div[contains(@class, 'line-block')])]|.//caption[not(descendant::p|descendant::li|descendant::caption|descendant::figcaption|descendant::dt|descendant::dd|descendant::blockquote|descendan …
```

improve xpath for building search index

---

inst/assets/BS4/pkgdown.css
inst/templates/BS4/head.html

The main difference in styling is that the active/hover item now gets a border radius to match the navbar. But it was very hard to see what was going with the combination of bootstrap-toc styling and manual overrides, so I dropped the default styling.

Tweak styling of TOC

---

R/build-search-docs.R

Fix #1680
Thanks to report by @mcanouil in https://github.com/r-lib/pkgdown/issues/1680#issuecomment-838628384
Something to keep in mind too if one day pkgdown keeps website of different releases.

Do not include dev website paths in search index of production website

---

R/context.R
R/init.R

Fix #1730 
I ended up noticing the structure of the article index produced by pkgdown and set as option `downlit.article_index` was different from the ones downlit creates for source packages.
In downlit, `find_article()` will recognize an article if its name is in the names of a vector. Then what it returns is the path relative to the article path (e.g. "usethis.html" or "articles/usethis-setup.html").
Edit: no fix is needed in downlit. On its own downlit would only produce an article index with _vignettes_. `downlit:::article_index_remote("googledrive")` is wrong because it uses the metadata published by pkgdown.
``` r
pkgload::load_all("/home/maelle/Documents/pkgdown/googledrive")
#> ℹ Loading googledrive
#> ! Internal auth failed; calling `drive_deauth()`. …
```

article_index fix

---

NEWS.md
R/render.r
inst/templates/BS4/navbar.html

Apply usual logic to search.json location rather than faulty special one

---

pkgdown/_pkgdown.yml

Fix #1766 h/t @cderv 
Upside: one can now choose a logical order.
Downside: having to choose that logical order.
AFAIK there's no way to use `starts_with` "except stuff already listed elsewhere".

Fix duplication in reference index

---

vignettes/linking.Rmd

I realized that, though I'd documented this in the build docstring, it wasn't yet documented in the linking vignette, so I thought I'd describe it there too.

Describe "deploy$install_metadata" config option in linking vignette

---

NEWS.md
R/rd-data.R
R/rd-html.R
tests/testthat/test-rd-data.R
tests/testthat/test-rd-html.R

`\value{}` can have multiple item/text blocks

---

NEWS.md
R/development.R
tests/testthat/test-development.R

Fixes #1768
@jennybc I'm pretty sure this is the correct logic (and hopefully you can follow it with too much of the pkgdown context), but I'd appreciate a second pair of eyes.

Only set version tooltip if development mode set

---

NEWS.md
R/deploy-site.R

cfd478ef (Explicitly set the remote's branch before fetching,
2020-03-25) made deploy_to_branch() call `git remote set-branches`
before fetching.  This prevents the downstream `git worktree --track`
call from failing in shallow clones (#1271), or more generally
whenever `remote.{remote}.fetch` is set to a refspec that excludes
gh-pages (or whatever the specified deploy branch is).
However, the set-branches call overwrites the configured value
entirely.  For example, if a remote 'origin' that has the default
`+refs/heads/*:refs/remotes/origin/*` refspec, that will be rewritten
to `+refs/heads/gh-pages:refs/remotes/origin/gh-pages`.  When the user
next calls `git fetch origin` expecting to bring in all of the
standard refs, only the gh-pages ref will be updated.
Avoid this problem by …

deploy_to_branch: Don't clobber remote's configured refspec

---

R/rmarkdown.R
tests/testthat/assets/articles-resources/DESCRIPTION
tests/testthat/assets/articles-resources/vignettes/resources.Rmd
tests/testthat/test-build-articles.R

When external resources are introduced by R code during the render process, `rmarkdown::find_external_resources()` will miss those resources because they aren't statically discoverable from the source of the document.
In the tests, I used this markdown to illustrate the issue
```markdown
```
I think we can squeeze a little bit more out of `rmarkdown::find_external_resources()` by temporarily copying the rendered article back into the source folder and scanning the `.html` file again. In the above case, this method will discover `<img src="external.png" />` and correctly move the file to the documentation destination.
This PR is on the path toward creating a gallery template where we'd like pkgdown to discover local images if they are inserted dynamically by R code called inside an R …

Find external article resources from rendered HTML

---

NEWS.md
R/tweak-tabset.R
tests/testthat/test-tweak-tabset.R

Fixes #1914 by keeping the tab title as an `xml_nodeset` using `xml2::xml_contents()`.
Repeating the reprex from #1914:
``` r
pkgload::load_all()
#> ℹ Loading pkgdown
html <- markdown_to_html("
Contents 1
Contents 2
Contents of normal tab
")
tweak_tabsets(html)
print_xpath_html_and_text <- function(x, xpath) {
x <- xml2::xml_find_first(x, xpath)
print(as.character(x))
xml2::xml_contents(x)
}
```
We now keep the `<code>` formatting in the tab title for the first tab
```r
print_xpath_html_and_text(html, ".//*[@id = 'toc-1-tab']")
#> [1] "<button data-bs-toggle=\"tab\" data-bs-target=\"#toc-1\" id=\"toc-1-tab\" type=\"button\" role=\"tab\" aria-controls=\"toc-1\" aria-selected=\"true\" class=\"active nav-link\">Tab 1 <code>with_code</code></button>"
#> {xml_nodeset (2)}
#> [1] Tab 1 
#> [2] …
```

Preserve HTML in tabset tab titles

---

R/build-footer.R
man/rmd-fragments/footer-configuration.Rmd
tests/testthat/test-build-footer.R

Adds a `package` component to the built-in footer components, allowing patterns such as
```yaml
footer:
structure:
left: [package, universe]
components:
universe: |
is part of a universe of packages...
```
which will render in the pkgdown pages as
> pkgdown is part of a universe of packages
(with the name of the package being documented, not pkgdown, in the final text).

Adds a built-in `package` component to the footer

---

NEWS.md

trailingslash_redirect -> trailing_slash_redirect
Doc is ok: https://pkgdown.r-lib.org/reference/build_site.html#template with the code
https://github.com/r-lib/pkgdown/blob/dcec859cab08ff8852f5ee5ab09f3f57ec038805/R/build-home-index.R#L49
but current changelog is not
https://pkgdown.r-lib.org/news/index.html#html-css-and-js-2-0-0

typo in NEWS.md for configuration name

---

vignettes/customise.Rmd

For PR previews, the vignette links to [this example workflow](https://github.com/r-lib/pkgdown/blob/main/.github/workflows/pkgdown.yaml) which uses `nwtgck/actions-netlify@v1.1`. This netlify action searches the netlify access token in the environment variables with the name `NETLIFY_AUTH_TOKEN` and not `NETLIFY_TOKEN`. See https://github.com/nwtgck/actions-netlify/blob/9b51bd37bcaba08043fd9b0ba2ebba10fed202a2/README.md?plain=1#L49
This PR corrects the name.

Fix name of netlify access token environment variable

---

NEWS.md
inst/BS5/assets/pkgdown.js

Fixes #1959 by only initializing the TOC scrollspy when the `#toc` element exists. This probably also resolves #1889.

Don't initialize scrollspy when `#toc` element is missing

---

NEWS.md
R/build-news.R
R/tweak-page.R
tests/testthat/test-build-articles.R
tests/testthat/test-tweak-page.R

Adjust Rmd that use h1 as top-level headings

---

inst/BS5/assets/pkgdown.js

Fix #2023 
In the preview it might look it does not work... because the search index has absolute URLs so when using search you are directed to the real website. :zany_face: 
Hence a direct link where things work https://61eaa925c88dfdfcb02cfe12--pkgdown-dev.netlify.app/dev/reference/init_site.html?q=build#build-ignored-files
Cc @jayhesselberth

fix search highlighting

---

NEWS.md
R/rd-html.R
tests/testthat/test-rd-html.R

Parse alternative text for figure tag on multiple lines

---

NEWS.md
R/repo.R
tests/testthat/test-repo.R

Improve repo_auto_link() regexp

---

R/rd-data.R
tests/testthat/test-rd-data.R

fixes #2108 
A recent commit - https://github.com/r-lib/pkgdown/commit/d1321f91ecc543f06e6b76409eb95e5ff7579d6b - allowed whitespace in tag_items lists. This broke a parser that checked the first element of that list which led to this behaviour 
```r
pkgdown:::value2html("\\item{a}{b}\n\n\\item{c}{d}\n\n\\item{e}{f}")
#>  [1] "<dl>"              "<dt>a</dt>"        "<dd><p>b</p></dd>"
#>  [4] ""                  ""                  "<dt>c</dt>"       
#>  [7] "<dd><p>d</p></dd>" ""                  ""                 
#> [10] "<dt>e</dt>"        "<dd><p>f</p></dd>" "</dl>"
pkgdown:::value2html("\n\\item{a}{b}\n\n\\item{c}{d}\n\n\\item{e}{f}")
#> [1] "<p></p>" "<p></p>" "<p></p>"
```
Function arguments in Rd files seem to be starting with a new line and therefore the function arguments …

Function arguments in reference aren't dropped by leading whitespace

---

NEWS.md
R/build-home-authors.R
tests/testthat/test-build-home-citation.R

Fix https://github.com/ropensci-org/rotemplate/issues/93

Escape angle brackets for URLs in author comments

---

NEWS.md
vignettes/metadata.Rmd

Fix #2185 (thank you, @Bisaloo!)

docs: remove mention of Twitter card validator; provide alternatives

---

R/tweak-homepage.R
tests/testthat/test-tweak-homepage.R

Why is badge extraction so confusing :zany_face: 
Fix #2060 (misdiagnosed, for a first paragraph it should not matter whether both usethis-like comments are present since badges extraction falls back on the first paragraph)
_Motivated by rOpenSci template but potentially problematic for other niches? :sweat_smile:_
In rotemplate [for Matomo usage](https://fr.matomo.org/faq/how-to/faq_176/#enable-tracking-for-visitors-who-have-javascript-disabled) there is a `p` **outside of the body** that the current XPath for detecting the "first paragraph" was picking. 
In this PR I am making the XPath specific to the first paragraph in the body.
Doing so I broke the tests, that were not testing what they were supposed to: in these tests badges were extracted thanks to being in the first paragraph. …

fix detection of first paragraph for badges

---

.Rbuildignore

This is part of me metaphorically closing all my browser tabs re: the `tools/` folder (https://github.com/r-lib/usethis/issues/1698).
I don't think this is super important. But it also doesn't seem to make sense to ship this script with pkgdown. So we could Rbuildignore it (current PR) or, alternatively, move [`syntax-highlight.R`](https://github.com/r-lib/pkgdown/blob/main/tools/syntax-highlight.R) to `data-raw/`.

Rbuildignore `tools/`

---

NEWS.md
R/tweak-reference.R
tests/testthat/test-highlight.R

fix: nested non R code blocks in manual pages

---

NEWS.md
R/topics.R
tests/testthat/test-topics.R

Fix #2234 
Note that this error depends on the _order_ of match strings inside a section. 
- If the first match string matches nothing, but the second one does match something, all topics are selected; 
- which is not the case when the first match string matches something but the second one does not match anything.
This is why I added two expectations in the new test: with the code in the main branch, only the second expectation fails.
Why is the check argument of `select_topics()` always set to FALSE? When there's a match string that matches nothing, shouldn't there be a warning or error?

fix: topic selection when one keyword matches and the other not

---

NEWS.md
R/usage.R

When a single documentation entry (say, a function) contains multiple `@usage` entries with the same function name, this leads to duplicate entries in the ‘pkgdown’ reference entry.
A concrete use-case can be found [in the ‘box’ package](https://github.com/klmr/box/blob/5ddbc725a873a195cc423a6da4417d05015c58fe/R/file.r#L3-L4):
```r
#' …
#' @usage \special{box::file(\dots)}
#' @usage \special{box::file(\dots, module)}
#' …
#' @export
file = function (..., module) {…}
```
Currently this is rendered as follows:
This PR removes redundant entries in the rendered reference index and adds a relevant test case. I have also added a test case for the similar case of an S3 method that is documented on the same page as its generic. This use-case is currently *not* affected by the duplicate-entry …

Deduplicate entries in reference index

---

vignettes/how-to-update-released-site.Rmd

It seems that GitHub changed how the search queries work. 
path:"_pkgdown.yml" for an exact match. (this is possibly excluding pkgdown/_pkgdown.yml. But the point here is to get accurate results, so this pinpoints to exactly what is required.
Changed the conditions, needed a OR between r-lib and tidyverse

Edit GitHub syntax to see _pkgdown.yml config advice

---

man/rmd-fragments/authors-configuration.Rmd

Fix  #2282
Maybe it'd also need a note on empty alternative text in case that's the best solution (reminded of this by #2288)

docs: add alternative text to example of author configuration

---

NEWS.md
R/tweak-reference.R
tests/testthat/test-tweak-reference.R

Fix #2298 
Thanks @salim-b for the report!

fix: preserve 'rmd' code chunks in Rd

---

NEWS.md
R/usage.R
tests/testthat/test-usage.R

`\method{}`, unlike `\S4method{}`, requires non-syntactic names to be escaped with backticks, so we don't need to escape again.
Fixes #2384

Parse S3 methods with non-syntactic names

---

NEWS.md
inst/BS5/templates/navbar.html

Fixes #2387 
Bootstrap 5.3 docs [suggest](https://twbs-bootstrap.netlify.app/docs/5.3/components/navbar/#color-schemes) that `.navbar-dark` is now deprecated in favour of using a data attribute `data-bs-theme="dark"`, which seems to facilitate client-side light/dark mode switching. 
In contrast to the proposed fix within the issue, this PR adds the new attribute without removing the old class, so as to maintain backwards compat with bslib <0.6

Fix BS5 navbar template to get `navbar.type: dark` to work with bslib 0.6+

---

man/rmd-fragments/footer-configuration.Rmd

As the default is `developed_by`. Currently, using this template, it prints NULL. Another solution would be to add the component `authors`, like so
```yaml
components:
legal: Provided without **any warranty**.
authors: xyz
```

Update custom footer example

---

R/build-articles.R
R/build-favicons.R
R/build-reference-index.R
R/build.R
R/check.R
R/package.R
man/build_site.Rd
tests/testthat/_snaps/build-reference-index.md
tests/testthat/_snaps/check.md

In current dev, the link created by `check_pkgdown()` if success was invalid if using `check_pkgdown("C:/users/path/to/package/")`. This PR fixes it as well as doing some touchups on the cli conversion.
Tweaks to output of `check_pkgdown()`. I used a new helper function to ensure that `check_pkgdown()` works if you provide `pkg`. 
Currently, it didn't work as expected. Also added some chaining, so that it would display Error in `check_pkgdown()` instead of Error in `check_missing_topics()`.
Also took advantage of cli inline markup for `{.pkg}`
FWIW, I am testing this with r-lib/devtools#2561 and it is working pretty well!

Tweaks in error chaining and path display

---

R/rd-html.R

Introduced in https://github.com/r-lib/pkgdown/pull/2378, the class of the unknown tags are never shown given that the string of the unknown tags is passed as second argument instead of string interpolation.
``` r
library(pkgdown)
pkgdown:::as_html.tag("test")
#> Message:
#> Unknown tag:
#> [1] ""
```
<sup>Created on 2024-02-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
Analogue to https://github.com/r-lib/pkgdown/pull/2378/files#diff-7800ebb360a3c28cd33101ef6ea07c562247ec30a029d0a69d527a80f17bff17L158-R164. I also changed the severity to warning.

Fix missing class name in "Unknown tag" message

---

R/package.R
R/utils.R
tests/testthat/test-init.R
tests/testthat/test-package.R

Fixes #2257. I wasn't exactly sure where to put the test, but figured it was better to include a brief test somewhere.
As with the other issue, I actually ran into this doing `build_site_github_pages()`, but figured it was better to fix at the root

fix override when included in `as_pkgdown`

---

R/render.R

fix regression introduced in #2378 
For example, after `init_site()` + `build_reference_index()`
2.0.7:
Current dev:
This PR brings back the old behavior.
Very useful for previewing easily.

Add back preview page runnable link

---

R/build.R

Before, directly calling `pkgdown:::build_site_external()` failed with
```
Error in `cli::cli_rule("Finished building pkgdown site for package {.pkg {pkg$package}}")`:
! Could not evaluate cli `{}` expression: `pkg$package`.
Caused by error in `pkg$package`:
! $ operator is invalid for atomic vectors
```
since `pkg = "." wasn't resolved to an actual `pkgdown` object`.

Fix `build_site_external()`

---

DESCRIPTION
R/build-favicons.R
R/build-home-index.R
R/development.R
R/sitrep.R
R/theme.R
R/topics.R
R/utils-yaml.R
tests/testthat/_snaps/build-favicons.md
tests/testthat/_snaps/build-home-index.md
tests/testthat/_snaps/build-redirects.md
tests/testthat/_snaps/build-reference-index.md
tests/testthat/_snaps/development.md
tests/testthat/_snaps/package.md
tests/testthat/_snaps/render.md
tests/testthat/_snaps/sitrep.md
tests/testthat/_snaps/topics.md
tests/testthat/_snaps/utils-yaml.md
tests/testthat/test-build-favicons.R
tests/testthat/test-utils-yaml.R

If `pkg` is not available within the functions
Added a couple of `call` to improve error messages as I saw them. Sorry the PR is not very focused. Sometimes it is hard to come back to it later...
Also the many changes in snapshots are caused by the fact that `{.file }` quotes in non-interactive, while `cli::style_hyperlink()` doesn't.
Addresses #2329

Add advice to use `usethis::edit_pkgdown_config()`

---

NEWS.md
R/build-articles.R
R/build-news.R
R/build-reference.R
R/build-tutorials.R
R/init.R
R/utils-fs.R

Fixes #2329.
Supersedes #2411 
Applies the suggestions to call `init_site()` earlier.
Will be interesting to see the codecov patch, maybe some messages are no longer reached?
Errors are caused by the fact that `init_site()` is called earlier, which triggers a message.

Avoid creation of faulty site

---

.github/workflows/pkgdown.yaml

Just saw the typo while trying to understand the page deployment github action

Fix typo in comment in pkgdown.yaml

---

NEWS.md
R/package.R
R/pkgdown.R
tests/testthat/_snaps/templates.md
tests/testthat/test-templates.R

Fixes #2440
Supercedes #2441
cc @maelle
Bootstrap versions can come from two places:
1. The local pkgdown config of the package being documented
2. The pkgdown config of a template package used by the package being documented
Unfortunately, they're interconnected: A local pkgdown config may set a Bootstrap version that then changes the template used by the template package. OR a template package may provide the Bootstrap version, not sepcificied in the local config. I missed this nuance in #2395.
This PR updates the Bootstrap version check to first call `get_boostrap_version()` on the local `pkg` config. Then we separately call `get_boostrap_version()` for the template. This function throws if both `template.bootstrap` and `template.bslib.version` are used in the same config. The separate …

fix: Use bootstrap version from template package if not defined locally

---

NEWS.md
R/build-articles.R
man/rmd-fragments/navbar-configuration.Rmd

Addresses https://github.com/r-lib/pkgdown/issues/2150#issuecomment-2053756994 + amends #2161
Basically, this allows to omit `articles/packagename` from articles reference index.
I did some manual testing switching pkgdown.Rmd to articles/pkgdown.Rmd
The goal of this PR is to remove this line from `_pkgdown.yml` for leaflet.
https://github.com/rstudio/leaflet/blob/92bc272caa9a268140e75ede1966bcdc7d585636/pkgdown/_pkgdown.yml#L57
I didn't understand why I had to do this in leaflet when I created its pkgdown site, but after reading #2150, I understood that pkgdown could handle this more intuitively !
The advantage of this PR is also that possibly, packages with `.` in them will be better off (although I didn't test this)
With:
```r
article_is_intro
function(name, package) {
package <- …
```

tweaks to detection of intro vignette

---

NEWS.md
inst/BS5/assets/pkgdown.scss
inst/BS5/templates/footer.html

The footer markdown is processed with `markdown_text_block()` so it always produces a block tag, rendering the wrapping `<p>` in the footer unnecessary. The empty paragraph tag ends up at the top of the footer, due to xml2 round trip.
Fixes #2381
@gadenbuie: do you mind taking a quick look at this since it's related to the PR you just reviewed?

Remove `<p>` from template

---

R/build.R
man/build_site.Rd

Fixes #2304
@juliasilge do you mind pointing me to the commit where you ended up implementing what you needed? Maybe I also need to update the google example?

Polish analytics docs

---

tests/testthat/_snaps/build-articles.md
tests/testthat/_snaps/build-favicons.md
tests/testthat/_snaps/build-github.md
tests/testthat/_snaps/build-home-citation.md
tests/testthat/_snaps/build-home.md
tests/testthat/_snaps/build-news.md
tests/testthat/_snaps/build-reference.md
tests/testthat/_snaps/figure.md
tests/testthat/setup.R

I removed this primarily because it globally suppresses cli output after you run any test file interactively, but IMO it also increases the fidelity of the snapshots.

Don't globally change cli.default_handler for tests

---

NEWS.md
R/markdown.R
tests/testthat/test-markdown.R

Fixes #2309
Rather than erroring, I just made it return nothing, which seems most consistent with the other ways we process markdown.

Work with empty markdown files

---

NEWS.md
R/tweak-tags.R
tests/testthat/test-tweak-tags.R

Also tweak urls with fragment

---

vignettes/customise.Rmd

Document how to use a non-Google font

---

NEWS.md
R/tweak-tags.R
tests/testthat/test-tweak-tags.R

Fixes #2402
@yjunechoe does this work for you?

Tweak source srcrefs

---

R/build-articles.R
R/rmarkdown.R
tests/testthat/_snaps/rmarkdown.md

Continue to refine build_articles() error

---

NEWS.md
R/theme.R
tests/testthat/_snaps/templates.md
tests/testthat/test-render.R
tests/testthat/test-templates.R

Updates `get_bslib_theme()` to support `template.bslib.bootswatch`. 
The Boostrap preset theme (a.k.a. Bootswatch) can be included in several places. `get_bslib_theme()` will use the first available (see order below), warning if different themes are specified in more than one place.
```yaml
template:
bootstrap: 5
bootswatch: pulse # <3>
bslib:
preset: united # <1>
bootswatch: simplex # <2>
params:
bootswatch: quartz # <4>
```
Using the above snippet in a `_pkgdown.yml` would result in the following:
```r
pkg <- local_pkgdown_site(meta = '
template: 
bootstrap: 5 
bootswatch: pulse # <3> 
bslib: 
preset: united # <1> 
bootswatch: simplex # <2> 
params: 
bootswatch: quartz # <4>
')
get_bslib_theme(pkg)
#> Warning: Multiple Bootstrap preset themes were set. Using "united" from
#> …
```

fix(template.bslib): Support bootswatch item

---

NEWS.md
R/build-favicons.R
R/build-logo.R
R/build-reference.R
R/init.R
R/package.R
R/templates.R
R/theme.R
R/utils-fs.R
tests/testthat/_snaps/build-articles.md
tests/testthat/_snaps/build-logo.md
tests/testthat/_snaps/init.md
tests/testthat/test-init.R

* Once again show one file per line
* Make it possible to nicely label special roots (i.e. the pkgdown package)
@jayhesselberth I can't remember if we discussed this at the time, but `cli::cli_inform()` always collapses to a single string, so I think the easiest way to get one line per file is to use `walk2()`.
Fixes #2445

Revamp messaging when copying files

---

NEWS.md
R/package.R
R/utils-fs.R
tests/testthat/_snaps/utils-fs.md
tests/testthat/test-utils-fs.R

Don't prompt user to install template package from CRAN

---

R/context.R
tests/testthat/test-init.R

This is a pragmatic fix so that autolinking for bslib should start working again.
Fixes #2350

Include full article path in site metadata

---

R/build-articles.R
R/build-home-authors.R
R/build-home-index.R
R/build-redirects.R
R/build-reference-index.R
R/check.R
R/markdown.R
R/navbar.R
R/package.R
R/pkgdown.R
R/sitrep.R
R/theme.R
R/utils-yaml.R
tests/testthat/_snaps/build-articles.md
tests/testthat/_snaps/build-home-index.md
tests/testthat/_snaps/build-redirects.md
tests/testthat/_snaps/build-reference-index.md
tests/testthat/_snaps/check.md
tests/testthat/_snaps/markdown.md
tests/testthat/_snaps/navbar.md
tests/testthat/_snaps/package.md
tests/testthat/_snaps/render.md
tests/testthat/_snaps/sitrep.md
tests/testthat/_snaps/templates.md
tests/testthat/_snaps/utils-yaml.md
tests/testthat/test-build-home-authors.R
tests/testthat/test-markdown.R
tests/testthat/test-navbar.R
tests/testthat/test-utils-yaml.R

* Create `config_abort()` with standard message pointing to `_config.yaml`
* That simplifies `pkgdown_field()`, which after a couple of steps got refactored away.
Part of #1927.
@olivroy would you be interested in reviewing this?

Refactor config error messages

---

R/rmarkdown.R

This eliminates some warnings that appear when building the pkgdown site itself.

Only do html operations for html vignettes

---

R/rmarkdown.R

The cli functions evaluate things in braces.
Errors may include braces that we do not want to evaluate
For instance, pkgdown was reporting an error when building my vignettes:
```
Error in `map()`:
i In index: 1.
Caused by error:
! Could not evaluate cli `{}` expression: `document`.
Caused by error:
! object 'document' not found
```
Because the rendering of my vignette reported:
```
LaTeX Error: Missing \begin{document}.
```
and `cli_abort` intepreted `{document}` as an
object to be evaluated.
Now it reports:
```
Error in `build_article()`:
! Failed to render vignettes/...
x ! LaTeX Error: Missing \begin{document}.
...
```
as expected

Fix cli evaluating brace contents in error msgs

---

NEWS.md
pkgdown/_pkgdown.yml
vignettes/accessibility.Rmd
vignettes/customise.Rmd
vignettes/pkgdown.Rmd

Including advice fixing the colour contrast issue caused by using the danger colour on a light navbar background (and apply that advice to pkgdown itself)
Fixes #2344. Fixes #2283.

Create accessibility vignette

---

R/build-home-index.R
R/build-reference.R
R/build-search-docs.R
R/deploy-site.R
R/pkgdown.R
R/theme.R
R/utils-fs.R
tests/testthat/test-build-articles.R
tests/testthat/test-build-home-index.R
tests/testthat/test-build-news.R
tests/testthat/test-build-redirects.R
tests/testthat/test-build-reference.R
tests/testthat/test-navbar.R
tests/testthat/test-package.R

Consistently use `path()`, not `file.path()`

---

vignettes/test/rendering.Rmd

Fixes new warnings about missing alt-text.
Sites re-built with the next release may see a *lot* of alt-text warnings (I don't typically include `fig.alt`, but I guess I should).

Add alt text to vignette

---

R/build-home.R

I didn't realize I was missing this one.
To finalize on #2439. 
With this PR, all  `build_*()` work without `init_site()`.
fyi `fs::path("dir", "")` = "dir" but fs::path("dir", NULL) gives `character(0)`.
Make `init_site()` even less relevant for previewing a site part!

build_home and build_home_index were the last site parts components you couldn't call directly without init_site()

---

R/navbar.R
inst/BS5/assets/pkgdown.scss
inst/BS5/templates/navbar.html
tests/testthat/test-navbar.R

@jayhesselberth does this make sense to you? It slightly changes the colour (hopefully not too noticeably), but computes them in such a way that switching to dark mode should be easier.

Update navbar styling to use data-bs-theme attribute

---

NEWS.md
R/build-articles.R
R/navbar.R
R/package.R
inst/BS3/templates/content-article-index.html
inst/BS5/templates/content-article-index.html
man/build_articles.Rd
tests/testthat/_snaps/build-articles.md
tests/testthat/test-build-articles.R

Fixes #2028
@EmilHvitfeldt as well as taking a look at the code, I'd really appreciate it if you could try it out on a tidymodels website just to check that it has all the features you need.

Add support for "external" articles

---

NEWS.md
R/package.R
tests/testthat/test-package.R

Only extract lifecycle badges from description

---

R/build-article.R
R/build-news.R
R/check.R
R/config.R
R/package.R
R/render.R
R/theme.R
tests/testthat/_snaps/build-article.md
tests/testthat/_snaps/build-articles.md
tests/testthat/_snaps/build-footer.md
tests/testthat/_snaps/build-home-authors.md
tests/testthat/_snaps/build-home-index.md
tests/testthat/_snaps/build-news.md
tests/testthat/_snaps/build-redirects.md
tests/testthat/_snaps/build-reference-index.md
tests/testthat/_snaps/check.md
tests/testthat/_snaps/config.md
tests/testthat/_snaps/markdown.md
tests/testthat/_snaps/navbar.md
tests/testthat/_snaps/package.md
tests/testthat/_snaps/render.md
tests/testthat/_snaps/templates.md
tests/testthat/_snaps/theme.md
tests/testthat/test-render.R
tests/testthat/test-theme.R

To always show path at the beginning
@jayhesselberth @maelle what do you think of this style? I like it because it allows us to reuse more code when producing errors for Rmd metadata. If you like the basic idea, I'll spend a bit more time polishing the code before merging the PR. It'll also make it easier to integrate #2549, so that whenever the error occurs in a GHA, you'll get an annotation on the file that caused the problem.

Unify config error messages

---

NEWS.md
R/usage.R
tests/testthat/test-usage.R

Wrap non-syntactic method names in backquotes

---

NEWS.md
R/rd-data.R
tests/testthat/test-rd-data.R

This is a good example of where _not_ to apply vectorised thinking because it's much clearer what's going on when we think about the current and previous item.
Fixes #2371

Improve `describe_contents()` parsing algorithm

---

NEWS.md
R/build-news.R
tests/testthat/test-build-news.R

We don't need to do it in `data_news()` because `render_page()` will handle it.
Fixes #2630

Only syntax highlight news once

---

vignettes/customise.Rmd

Minor typo,
But while I was reading the vignette, some thoughts occured to me. Just thought I'd share them as the timing seems right (actively working on pkgdown 2.1, and closed more than 100 issues in a few weeks(?!) you are a machine!)
I wanted to share my thoughts on my last pain point when iterating and customizing a site locally: `init_site()` or no `init_site()`.
In this type of workflow, now allowed with #2439 and #2571, I find step 0.1 to be the most nebulous 
0. `usethis::use_pkgdown()`
0.1 `init_site()` (only needed sometimes?)
1. Edit _pkgdown.yml or other site components (adding a logo, color, changing font, layout etc.)
2.  `build_home()`
4. Preview page
5. Repeat (1-3)
In short, I'd want to know what **special** edits to site config  (1) requires manually running …

Fix typo in vignette

---

NEWS.md
R/autolink_html.R
R/build-reference.R
R/build.R
man/autolink_html.Rd
man/build_reference.Rd
man/build_site.Rd

Remove `document` from `build_site()` and `build_reference()` + warn on `autolink_html()`

Remove `document`, and warn on `autolink_html()` usage

---

po/R-es.po

Hi @hadley and **pkgdown** team:
I updated the Spanish translation file (see #2659). As in the case of #2663 I didn't compile it yet as I suppose you may prefer to compile all the translation at once and avoid conflicts with subsequent PRs on this issue.
Regards

Update Spanish translation

---

R/templates.R

Follow up from https://github.com/r-lib/pkgdown/pull/2556.
This triggers an error in template packages that provide template elements which don't exist in pkgdown, such as the [`carpentries/varnish`](https://github.com/carpentries/varnish) package.
```
Error in `purrr::map_chr()`:
ℹ In index: 5.
Caused by error in `map_()`:
! Can't find template for "content-chapter".
---
Backtrace:
▆
1. └─sandpaper::build_lesson()
2.   └─sandpaper:::build_site(...)
3.     └─sandpaper::build_episode_html(...)
4.       └─sandpaper:::build_html(...)
5.         └─pkgdown::render_page(...)
6.           └─pkgdown:::render_page_html(pkg, name = name, data = data, depth = depth)
7.             └─purrr::map_chr(pieces, find_template, name = name, pkg = pkg)
8.               └─purrr:::map_("character", .x, .f, …
```

Fix typo which prevents finding templates

---

.github/workflows/netlify.yaml
NEWS.md
R/build-quarto-articles.R
tests/testthat/helper.R
tests/testthat/test-figure.R

partially addresses #2675 
I am seeing a lot of test-failure locally, maybe related to my setup? (under a proxy or without the right  quarto). I didn't see this last time I opened a PR #2645).
Maybe I misunderstood something? the netlify workflow doesn't require 1.5

Clarify that Quarto 1.5 is required.

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

No need to specify pre-release in GitHub actions. (sorry for comitting to main directly. I will be more careful.

Quarto1.5 is released

---

R/navbar.R
tests/testthat/_snaps/navbar.md
tests/testthat/test-navbar.R

* Add a test so I don't break it again!
* Finish off passing around caller to get correct call in error
Fixes #2673

Navbar components shouldn't be merged recursively

---

vignettes/quarto.qmd

Quarto 1.5 is now released so no need for pre-release

---

vignettes/customise.Rmd

I noticed that users who specify `right` have lost their `search` as part of pkgdown 2.1.0. So, I thought it'd be good to update the suggestion for template

Update customise.Rmd to advice for `search` on the right.

---

R/usage.R
tests/testthat/test-usage.R

This commit implements the change @hadley proposed at https://github.com/r-lib/pkgdown/issues/2727#issuecomment-2233517302 to the internal function `needs_tweak()`. This does resolve the small reproducible example I described, though I ignore if there are other situations where it wouldn't work for.

Resolve https://github.com/r-lib/pkgdown/issues/2727

---

tests/testthat/_snaps/build-reference-index.md

Since bslib has now registered its url in a way that downlit recognises.

Update snapshot tests

---

R/build-news.R
R/utils.R
tests/testthat/test-build-news.R

Fixes #2708 Eliminated stringsAsFactors from build-news, utils.r and testthat/build-news since it defaults R >= 4.0.0

Fixes #2708 eliminated stringsAsFactors from pkgdown

---

NEWS.md
R/build-home-index.R
tests/testthat/_snaps/build-home-index.md
tests/testthat/test-build-home-index.R

allow BugReports to be an email

---

.github/workflows/R-CMD-check.yaml
.github/workflows/lint.yaml
.github/workflows/netlify.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
DESCRIPTION
NEWS.md
vignettes/quarto.qmd

Closes #2743 
Updates quarto vignette and gha workflow files now that `setup-r-dependencies` automatically installs quarto as required.

updated gha instructions/workflows for quarto

---

vignettes/customise.Rmd
vignettes/how-to-update-released-site.Rmd
vignettes/linking.Rmd
vignettes/metadata.Rmd
vignettes/pkgdown.Rmd
vignettes/translations.Rmd

Proofread and edit vignettes for general spelling/grammar.

Proofread vignettes, fixes #2707

---

R/rd.R
tests/testthat/test-build-home-license.R
tests/testthat/test-build-reference.R
tests/testthat/test-rd-html.R

Remove code needed for old R versions

---

R/tweak-page.R
tests/testthat/test-tweak-page.R

Currently, there is an issue in `tweak_rmarkdown_html` which causes forward slash characters in generated `<img>` tags to be escaped during the conversion from absolute to relative paths, causing the images to not load correctly.
i.e.
`<img src="mysubdir/myimg.png">` 
becomes
`<img src="mysubdir%2Fmyimg.png">`
after the call to `tweak_rmarkdown_html`.
The proposed change preserves what I think is the intention of the original call to `xml2::url_esacpe` (to properly encode space characters) but adds the forward slash character as a reserved character to prevent it from being encoded. 
After this change, all existing tests continue to pass.
I'm happy to try and write a test case for this issue as well if necessary.
Thanks,
Andrew

Retain forward slashes in HTML img src paths

---

NEWS.md
R/markdown.R
R/render.R
R/tweak-page.R
tests/testthat/_snaps/markdown.md
tests/testthat/test-build-home-index.R
tests/testthat/test-markdown.R

They are being stripped out immediately after converting Markdown to HTML. This works for me in duckplyr: https://github.com/tidyverse/duckplyr/actions/runs/11086444293/job/30803979684 is built using this branch, the result is in https://duckplyr.tidyverse.org/ .
Not sure how to add tests here.

Support ANSI sequences in `index.md`

---

NEWS.md
R/package.R
tests/testthat/assets/reference-language/one/DESCRIPTION
tests/testthat/assets/reference-language/two/DESCRIPTION
tests/testthat/test-package.R

If the package authors have specified a Language in DESCRIPTION, default to that, rather than "en".

Respect DESCRIPTION language.

---

R/build.R
man/build_site.Rd
man/deploy_site_github.Rd
man/deploy_to_branch.Rd
man/init_site.Rd

Fix Google Analytic typo

---

NEWS.md
inst/BS5/assets/pkgdown.scss
vignettes/customise.Rmd

bslib patches Bootstrap to add three Sass variables: `$navbar-bg`, `$navbar-light-bg` and `$navbar-dark-bg` (see e.g. [bslib's Boostrap 5 `_variables.scss` file](https://github.com/rstudio/bslib/blob/e2ca5e0b5cb73a94d6bf049927a4a366fc3c231d/inst/lib/bs5/scss/_variables.scss#L1217-L1219)).
This PR updates pkgdown's Sass so that `$pkgdown-navbar-bg` and `$pkgdown-navbar-bg-dark` inherit the (default) values from bslib so that the same Sass variables can be used in Shiny, Quarto and pkgdown. 
This change shouldn't affect anyone who is already using the pkgdown Sass variables as these will take precedence over bslib's navbar bg vars.
Fixes #2703

feat: Use bslib's navbar Sass variables, if present

---

tests/testthat/_snaps/build-article.md
tests/testthat/test-build-article.R

for recent versions of Pandoc (which don't emit the `This document format requires a nonempty <title> element` warning for HTML output anymore).

test: fix `pandoc --fail-if-warnings` test

---

R/repo.R
tests/testthat/test-repo.R

GitLab returns HTTP status code [301 Moved Permanently](https://developer.mozilla.org/docs/Web/HTTP/Status/301) for issue tracker URLs like `https://gitlab.com/rpkg.dev/pal/issues` with new `location` header set to `https://gitlab.com/rpkg.dev/pal/-/issues`. Hence a missing `/-/` in the URL  triggers a `NOTE` about a possibly invalid URL during `devtools::check(remote = TRUE)`.
This PR adapts pkgdown to always generate `/-/issues/` URLs for GitLab.

fix: generate correct GitLab `/issues` URL

---

DESCRIPTION
NEWS.md
R/build-home-authors.R
R/build-home.R
inst/BS5/assets/pkgdown.scss
inst/BS5/templates/content-authors.html
inst/BS5/templates/content-citation-authors.html
man/deploy_site_github.Rd
man/deploy_to_branch.Rd
man/init_site.Rd
man/pkgdown-package.Rd
man/test-dont.Rd
tests/testthat/_snaps/build-home-authors.md
tests/testthat/_snaps/build-home-index.md
tests/testthat/test-build-home-authors.R

feat: add support for ROR

---

DESCRIPTION
tests/testthat/test-build-article.R

The next version of knitr will be a few months away, so this is a workaround for a patch pkgdown release that skips a snapshot test that depends on unreleased knitr.
https://github.com/yihui/knitr/issues/2399

Workaround for unreleased knitr version
